---
- sensor.main_bathroom_temperature
- sensor.main_bathroom_humidity
- light.bathroom
- light.bathroom_mirror
- light.ensuite_bathroom
- light.ensuite_bathroom_mirror
- sensor.washing_machine_running
- sensor.dryer_running
