---
- sensor.bedroom_temperature
- sensor.bedroom_humidity
- light.bedroom
- light.bed_led_strip
- light.dressing_room
- media_player.bedroom
- media_player.bedroom_tv
- script.vacuum_bedroom
- cover.bedroom
- binary_sensor.bedroom_occupancy
- switch.white_noise_music
