---
- sensor.living_room_temperature
- sensor.living_room_humidity
- sensor.living_room_illuminance_lux
- binary_sensor.living_room_occupancy
- media_player.living_room
- light.living_room
- light.dna_lamp
- light.christmas_tree
- cover.living_room
