---
binary_sensor:
  - platform: mqtt
    name: Alberto in Bed
    state_topic: "presence/main_bed/binary_sensor/alberto_in_bed/state"
    availability_topic: "presence/main_bed/status"
    qos: 1
  - platform: mqtt
    name: Judith in Bed
    state_topic: "presence/main_bed/binary_sensor/judith_in_bed/state"
    availability_topic: "presence/main_bed/status"
    qos: 1
  - platform: mqtt
    name: Anyone in Bed
    state_topic: "presence/main_bed/binary_sensor/anyone_in_bed/state"
    availability_topic: "presence/main_bed/status"
    qos: 1
  - platform: mqtt
    name: Everybody in Bed
    state_topic: "presence/main_bed/binary_sensor/everybody_in_bed/state"
    availability_topic: "presence/main_bed/status"
    qos: 1
