---
# The apartment we bought came with the "smart" system DigitalStrom. Our plan is
# to change the devices with a more open solution (Shellys running ESPHome) but
# for the moment, let's expose the entities into Home Assistant using the
# digitalstrom-mqtt bridge.
light:
  - platform: mqtt
    name: Kitchen
    command_topic: "digitalstrom/devices/Kitchen_Light/brightness/command"
    state_topic: "digitalstrom/devices/Kitchen_Light/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"
    retain: true
  - platform: mqtt
    name: Kitchen Focus
    command_topic: "digitalstrom/devices/Kitchen_Focus_Light/brightness/command"
    state_topic: "digitalstrom/devices/Kitchen_Focus_Light/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Office
    command_topic: "digitalstrom/devices/Office_Light/brightness/command"
    state_topic: "digitalstrom/devices/Office_Light/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Bedroom
    command_topic: "digitalstrom/devices/Main_Bedroom_Light/brightness/command"
    state_topic: "digitalstrom/devices/Main_Bedroom_Light/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Dressing Room
    command_topic: "digitalstrom/devices/Ankleide_Deckenleuchte/brightness/command"
    state_topic: "digitalstrom/devices/Ankleide_Deckenleuchte/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Kid's Room
    command_topic: "digitalstrom/devices/Zimmer_2_Deckenleuchte/brightness/command"
    state_topic: "digitalstrom/devices/Zimmer_2_Deckenleuchte/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Hallway
    command_topic: "digitalstrom/devices/Hallway_Light/brightness/command"
    state_topic: "digitalstrom/devices/Hallway_Light/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Dining Room
    command_topic: "digitalstrom/devices/Dinning_Room_Light/brightness/command"
    state_topic: "digitalstrom/devices/Dinning_Room_Light/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Living Room Switch
    command_topic: "digitalstrom/devices/Wohnen_Deckenleuchte/brightness/command"
    state_topic: "digitalstrom/devices/Wohnen_Deckenleuchte/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: North Balcony
    command_topic: "digitalstrom/devices/Loggia_Ost_Leuchte/brightness/command"
    state_topic: "digitalstrom/devices/Loggia_Ost_Leuchte/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: South Balcony
    command_topic: "digitalstrom/devices/Loggia_West_Leuchte/brightness/command"
    state_topic: "digitalstrom/devices/Loggia_West_Leuchte/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Bathroom
    command_topic: "digitalstrom/devices/Bathroom_Light/brightness/command"
    state_topic: "digitalstrom/devices/Bathroom_Light/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"
  - platform: mqtt
    name: Bathroom Mirror
    command_topic: "digitalstrom/devices/Bathroom_Mirror_Light/brightness/command"
    state_topic: "digitalstrom/devices/Bathroom_Mirror_Light/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"

  - platform: mqtt
    name: Ensuite Bathroom
    command_topic: "digitalstrom/devices/Dusche_Deckenleuchte/brightness/command"
    state_topic: "digitalstrom/devices/Dusche_Deckenleuchte/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"
  - platform: mqtt
    name: Ensuite Bathroom Mirror
    command_topic: "digitalstrom/devices/Dusche_Spiegel/brightness/command"
    state_topic: "digitalstrom/devices/Dusche_Spiegel/brightness/state"
    payload_on: "100.00"
    payload_off: "0.00"
cover:
  - platform: mqtt
    name: Living Room
    state_topic: "digitalstrom/devices/Wohnen_Store/shadePositionOutside/state"
    state_closed: "0.00"
    state_open: "100.00"
    command_topic: "digitalstrom/devices/Wohnen_Store/shadePositionOutside/command"
    payload_close: "0.00"
    payload_open: "100.00"
    payload_stop:
    position_topic: "digitalstrom/devices/Wohnen_Store/shadePositionOutside/state"
    set_position_topic: "digitalstrom/devices/Wohnen_Store/shadePositionOutside/command"
    position_template: "{{ value | int }}"
    tilt_status_topic: "digitalstrom/devices/Wohnen_Store/shadeOpeningAngleOutside/state"
    tilt_command_topic: "digitalstrom/devices/Wohnen_Store/shadeOpeningAngleOutside/command"
    tilt_status_template: "{{ value | int }}"
    retain: true
  - platform: mqtt
    name: Bedroom
    state_topic: "digitalstrom/devices/Main_Bedroom_Cover/shadePositionOutside/state"
    state_closed: "0.00"
    state_open: "100.00"
    command_topic: "digitalstrom/devices/Main_Bedroom_Cover/shadePositionOutside/command"
    payload_close: "0.00"
    payload_open: "100.00"
    payload_stop:
    position_topic: "digitalstrom/devices/Main_Bedroom_Cover/shadePositionOutside/state"
    set_position_topic: "digitalstrom/devices/Main_Bedroom_Cover/shadePositionOutside/command"
    position_template: "{{ value | int }}"
    tilt_status_topic: "digitalstrom/devices/Main_Bedroom_Cover/shadeOpeningAngleOutside/state"
    tilt_command_topic: "digitalstrom/devices/Main_Bedroom_Cover/shadeOpeningAngleOutside/command"
    tilt_status_template: "{{ value | int }}"
    retain: true
  - platform: mqtt
    name: Kid's Room
    state_topic: "digitalstrom/devices/Zimmer_2_Store/shadePositionOutside/state"
    state_closed: "0.00"
    state_open: "100.00"
    command_topic: "digitalstrom/devices/Zimmer_2_Store/shadePositionOutside/command"
    payload_close: "0.00"
    payload_open: "100.00"
    payload_stop:
    position_topic: "digitalstrom/devices/Zimmer_2_Store/shadePositionOutside/state"
    set_position_topic: "digitalstrom/devices/Zimmer_2_Store/shadePositionOutside/command"
    position_template: "{{ value | int }}"
    tilt_status_topic: "digitalstrom/devices/Zimmer_2_Store/shadeOpeningAngleOutside/state"
    tilt_command_topic: "digitalstrom/devices/Zimmer_2_Store/shadeOpeningAngleOutside/command"
    tilt_status_template: "{{ value | int }}"
    retain: true
  - platform: mqtt
    name: Office
    state_topic: "digitalstrom/devices/Office_Cover/shadePositionOutside/state"
    state_closed: "0.00"
    state_open: "100.00"
    command_topic: "digitalstrom/devices/Office_Cover/shadePositionOutside/command"
    payload_close: "0.00"
    payload_open: "100.00"
    payload_stop:
    position_topic: "digitalstrom/devices/Office_Cover/shadePositionOutside/state"
    set_position_topic: "digitalstrom/devices/Office_Cover/shadePositionOutside/command"
    position_template: "{{ value | int }}"
    tilt_status_topic: "digitalstrom/devices/Office_Cover/shadeOpeningAngleOutside/state"
    tilt_command_topic: "digitalstrom/devices/Office_Cover/shadeOpeningAngleOutside/command"
    tilt_status_template: "{{ value | int }}"
    retain: true
  - platform: mqtt
    name: Dining Room
    state_topic: "digitalstrom/devices/Essen_Store/shadePositionOutside/state"
    state_closed: "0.00"
    state_open: "100.00"
    command_topic: "digitalstrom/devices/Essen_Store/shadePositionOutside/command"
    payload_close: "0.00"
    payload_open: "100.00"
    payload_stop:
    position_topic: "digitalstrom/devices/Essen_Store/shadePositionOutside/state"
    set_position_topic: "digitalstrom/devices/Essen_Store/shadePositionOutside/command"
    position_template: "{{ value | int }}"
    tilt_status_topic: "digitalstrom/devices/Essen_Store/shadeOpeningAngleOutside/state"
    tilt_command_topic: "digitalstrom/devices/Essen_Store/shadeOpeningAngleOutside/command"
    tilt_status_template: "{{ value | int }}"
    retain: true
