input_datetime:
  echo_breakfast_time:
    name: Echo's Breakfast Time
    has_date: false
    has_time: true
  echo_dinner_time:
    name: Echo's Dinner Time
    has_date: false
    has_time: true
    
  echo_morning_walk_time:
    name: Echo's Morning Walk Time
    has_date: false
    has_time: true
  echo_afternoon_walk_time:
    name: Echo's Afternoon Walk Time
    has_date: false
    has_time: true
  echo_night_walk_time:
    name: Echo's Night Walk Time
    has_date: false
    has_time: true