---
sensor:
  - platform: statistics
    entity_id: sensor.energy_meter_total_kwh
    name: Energy Total kWh
  - platform: statistics
    entity_id: sensor.energy_meter_ct1_kwh
    name: Energy CT1 kWh
  - platform: statistics
    entity_id: sensor.energy_meter_ct2_kwh
    name: Energy CT2 kWh
  - platform: statistics
    entity_id: sensor.energy_meter_ct3_kwh
    name: Energy CT3 kWh
  - platform: statistics
    entity_id: sensor.energy_meter_ct4_kwh
    name: Energy CT4 kWh
  - platform: statistics
    entity_id: sensor.energy_meter_ct5_kwh
    name: Energy CT5 kWh
  - platform: statistics
    entity_id: sensor.energy_meter_ct6_kwh
    name: Energy CT6 kWh