---
sensor:
  - platform: mqtt
    name: "Volts"
    state_topic: "energy_meter/appartment/sensor/energy_metter_volts_a/state"
    availability_topic: "energy_meter/appartment/status"
    unit_of_measurement: "Volts"
  - platform: mqtt
    name: "Frequency"
    state_topic: "energy_meter/appartment/sensor/energy_metter_freq_a/state"
    availability_topic: "energy_meter/appartment/status"
    unit_of_measurement: "Hz"
  - platform: mqtt
    name: "Total Amps"
    state_topic: "energy_meter/appartment/sensor/energy_metter_total_amps/state"
    availability_topic: "energy_meter/appartment/status"
    unit_of_measurement: "Amps"
  - platform: mqtt
    name: "Total Watts"
    # yamllint disable-line rule:line-length
    state_topic: "energy_meter/appartment/sensor/energy_metter_total_watts/state"
    availability_topic: "energy_meter/appartment/status"
    unit_of_measurement: "Watts"
