light:
  - platform: flux_led_custom
    devices:
      172.16.1.10:
        name: sofa_led
        mode: "rgb"
  - platform: flux_led_custom
    devices:
      172.16.1.20:
        name: bed_led
        mode: "rgb"
  - platform: flux_led_custom
    devices:
      172.16.1.32:
        name: tv_led
        mode: "rgb"
        
  # - platform: mqtt
  #   name: "Dinner Table Light"
  #   state_topic: "zigbee2mqtt/dinner_table_light"
  #   availability_topic: "zigbee2mqtt/bridge/state"
  #   brightness: true
  #   color_temp: true
  #   schema: "json"
  #   command_topic: "zigbee2mqtt/dinner_table_light/set"

  - platform: mqtt
    name: Dining Room
    state_topic: "switches/dining_room/switch/dining_room_light/state"
    command_topic: "switches/dining_room/switch/dining_room_light/command"
    availability_topic: "switches/dining_room/status"
    # brightness_state_topic: "zigbee2mqtt/dining_table_light"
    # brightness_command_topic: "zigbee2mqtt/dining_table_light/set"
    # brightness_value_template: "{{ value_json.brightness }}"
    # on_command_type: "first"

  - platform: mqtt
    name: Living Room
    state_topic: "switches/living_room/switch/living_room_light/state"
    command_topic: "switches/living_room/switch/living_room_light/command"
    availability_topic: "switches/living_room/status"
    
  - platform: mqtt
    name: Bedroom
    state_topic: "switches/bedroom/switch/bedroom_light/state"
    command_topic: "switches/bedroom/switch/bedroom_light/command"
    availability_topic: "switches/bedroom/status"

  - platform: mqtt
    name: Office
    state_topic: "switches/office/switch/office_light/state"
    command_topic: "switches/office/switch/office_light/command"
    availability_topic: "switches/office/status"

  - platform: mqtt
    name: Corridor
    state_topic: "switches/corridor/switch/corridor_light/state"
    command_topic: "switches/corridor/switch/corridor_light/command"
    availability_topic: "switches/corridor/status"