---
light:
  - platform: template
    lights:
      living_room:
        friendly_name: Living Room Light
        value_template: "{{ states('light.living_room_switch') }}"
        temperature_template: >-
          {{ state_attr('light.living_room_bulbs', 'color_temp') }}
        color_template: >-
          ({{ state_attr('light.living_room_bulbs', 'color')['x'] }},
          {{ state_attr('light.living_room_bulbs', 'color')['y'] }})
        turn_on:
          service: light.turn_on
          data:
            entity_id: light.living_room_switch
        turn_off:
          service: light.turn_off
          data:
            entity_id: light.living_room_switch
        set_level:
          service: light.turn_on
          data:
            entity_id:
              - light.living_room_switch
              - light.living_room_bulbs
            brightness: "{{ brightness }}"
        set_temperature:
          service: light.turn_on
          data:
            entity_id:
              - light.living_room_switch
              - light.living_room_bulbs
            color_temp: "{{ color_temp }}"

  - platform: group
    name: LED Strips
    entities:
      - light.kitchen_led_strip_ceiling
      - light.kitchen_led_strip_floor
      - light.bed_led_strip
  - platform: switch
    name: DNA Lamp
    entity_id: switch.dna_lamp
  - platform: switch
    name: South Balcony Floor
    entity_id: switch.plug_switch_2
