---
light:
  # - platform: flux_led_custom
  #   devices:
  #     10.4.1.120:
  #       name: sofa_led
  #       mode: "rgb"
  # - platform: flux_led_custom
  #   devices:
  #     172.16.1.90:
  #       name: bed_led
  #       mode: "rgb"
  # - platform: flux_led_custom
  #   devices:
  #     172.16.1.135:
  #       name: tv_led
  #       mode: "rgb"

  - platform: "mqtt"
    name: Dining Table
    state_topic: "zigbee2mqtt/dining_table_light"
    availability_topic: "zigbee2mqtt/bridge/state"
    brightness: true
    color_temp: true
    xy: false
    hs: false
    schema: "json"
    command_topic: "zigbee2mqtt/dining_table_light/set"
    brightness_scale: 254
    max_mireds: 500
    min_mireds: 150
    effect: true
    effect_list:
      - "blink"
      - "breathe"
      - "okay"
      - "channel_change"
      - "finish_effect"
      - "stop_effect"
