---
sensor:
  # Living Room
  - platform: "mqtt"
    name: Living Room Occupancy Sensor Battery
    state_topic: "zigbee2mqtt/living_room_occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.battery }}"
    unit_of_measurement: "%"
    device_class: "battery"
  - platform: "mqtt"
    name: Living Room Illuminance
    state_topic: "zigbee2mqtt/living_room_occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.illuminance }}"
    unit_of_measurement: "lx"
    device_class: "illuminance"
  - platform: "mqtt"
    name: Living Room Occupancy Sensor Link Quality
    state_topic: "zigbee2mqtt/living_room_occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.linkquality }}"
    unit_of_measurement: "lqi"
    icon: "mdi:signal"

binary_sensor:
  # Living Room
  - platform: "mqtt"
    name: Living Room Occupancy
    state_topic: "zigbee2mqtt/living_room_occupancy"
    availability_topic: "zigbee2mqtt/bridge/state"
    value_template: "{{ value_json.occupancy }}"
    payload_on: true
    payload_off: false
    device_class: "motion"
