---
scene:
  - name: Daylight
    icon: "mdi:white-balance-sunny"
    entities:
      light.bed_led_strip: "off"
      cover.bedroom:
        state: open
        current_position: 100
      cover.dining_room:
        state: open
        current_position: 100
      cover.office:
        state: open
        current_position: 100
      cover.living_room:
        state: open
        current_position: 100
      cover.kid_s_room:
        state: open
        current_position: 100
      lock.entrance_door: unlocked
      humidifier.main_bedroom: "off"

  - name: Evening
    icon: "mdi:weather-sunset-down"
    entities:
      cover.bedroom:
        state: closed
        current_position: 0
        current_tilt_position: 0
      cover.kid_s_room:
        state: closed
        current_position: 0
        current_tilt_position: 0
      # light.bed_led_strip: "on"
      light.kid_s_room: "on"
      switch.white_noise_music: "on"
      humidifier.main_bedroom: "on"

  - name: Night
    icon: "mdi:moon-waning-crescent"
    entities:
      light.bedroom: "off"
      light.bed_led_strip: "off"
      light.dining_room: "off"
      light.hallway: "off"
      light.kitchen: "off"
      light.kitchen_focus: "off"
      light.living_room: "off"
      light.office: "off"
      light.office_wall_lines: "off"
      light.kid_s_room: "off"
      media_player.living_room_tv: "off"
      lock.entrance_door: locked
      switch.white_noise_music: "off"
