---
alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_code

template:
  - binary_sensor:
      - name: Motion at Home
        # We need to filter the self entity as it will lead to a feedback loop
        # that will keep the sensor `on` forever.
        state: >-
          {{
            states.binary_sensor
            | selectattr('attributes.device_class', 'eq', 'motion')
            | selectattr('entity_id', '!=', 'binary_sensor.motion_at_home')
            | map(attribute='state')
            | select('eq', 'on')
            | list
            | count > 0
          }}
        device_class: motion
