---
alarm_control_panel:
  - platform: manual
    name: Alarm
    code: !secret alarm_code

template:
  - binary_sensor:
      - name: Motion at Home
        state: >-
          {{
            states.binary_sensor
            | selectattr('attributes.device_class', 'eq', 'motion')
            | map(attribute='state')
            | select('eq', 'on')
            | list
            | count > 0
          }}
        device_class: motion
