---
media_player:
  - platform: group
    name: Sonos Speakers
    entities:
      - media_player.dining_room
      - media_player.kids_room
      - media_player.living_room
      - media_player.main_bedroom
      - media_player.office
