---
sensor:
  # Mold indicators.
  - platform: mold_indicator
    name: Mold Indicator Bedroom
    indoor_temp_sensor: sensor.bedroom_temperature
    indoor_humidity_sensor: sensor.bedroom_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.0
  - platform: mold_indicator
    name: Mold Indicator Living Room
    indoor_temp_sensor: sensor.living_room_temperature
    indoor_humidity_sensor: sensor.living_room_humidity
    outdoor_temp_sensor: sensor.outside_temperature
    calibration_factor: 1.0

  # Average Climate values for all the inside house.
  - platform: min_max
    type: mean
    name: Inside Temperature
    entity_ids:
      - sensor.living_room_temperature
      - sensor.bedroom_temperature
      - sensor.bathroom_temperature
      # This comes from the Dyson fan defined in climate.yaml.
      - sensor.office_temperature
  - platform: min_max
    type: mean
    name: Inside Humidity
    entity_ids:
      - sensor.living_room_humidity
      - sensor.bedroom_humidity
      - sensor.bathroom_humidity
      # This comes from the Dyson fan defined in climate.yaml.
      - sensor.humidity
  - platform: min_max
    type: mean
    name: Inside Pressure
    entity_ids:
      - sensor.living_room_pressure
      - sensor.bedroom_pressure
      - sensor.main_bathroom_pressure
