---
vacuum:
  - platform: xiaomi_miio
    name: Xiaomi Vacuum Cleaner
    host: !secret xiaomi_vacuum_ip
    token: !secret xiaomi_vacuum_token

input_select:
  vacuum_room:
    name: Choose a room to clean
    options:
      - Select Input
      - Kitchen
      - Living Room
      - Main Bedroom
      - Hallway
      - Office
      - Kid's Room
      - Bathroom
    initial: Select Input

input_boolean:
  vacuum_clean_when_leave_home:
    name: Vacuum Clean When Leave Home
    icon: mdi:spray-bottle
