---
garbage_collection:
  sensors:
    - name: Cardboard Waste
      frequency: "odd-weeks"
      collection_days: sat
      expire_after: "08:00"
      verbose_state: true
      icon_normal: mdi:package-variant
    - name: Paper Waste
      frequency: "monthly"
      collection_days: sat
      expire_after: "08:00"
      verbose_state: true
      icon_normal: mdi:newspaper-variant-multiple-outline
      weekday_order_number: 4
