---
weather:
  - platform: darksky
    api_key: ebd7db258e14c7f89c5a48f8b110bcc7
    name: Weather
    mode: daily

sensor:
  - platform: darksky
    api_key: ebd7db258e14c7f89c5a48f8b110bcc7
    monitored_conditions:
      - temperature
      - humidity
      - apparent_temperature
      - minutely_summary
      - hourly_summary
      - daily_summary

# Track the sun
sun:

template:
  - sensor:
      - name: Wind Speed
        state: "{{ state_attr('weather.weather', 'wind_speed') }}"
        unit_of_measurement: "m/s"
        state_class: measurement
        icon: "mdi:weather-windy"
