---
binary_sensor:
  - platform: workday
    country: CH
    province: ZH

template:
  binary_sensor:
    - name: Alberto Working
      state: >-
        {{
          is_state('binary_sensor.macbook_pro_google_active', 'on')
          and
          not is_state('device_tracker.macbook_pro_google', 'away') 
        }}
      delay_off: "00:02:00"
      icon: "mdi:briefcase"
      device_class: occupancy
    - name: Alberto in Working Meeting
      state: >-
        {{
          is_state('binary_sensor.macbook_pro_google_camera_in_use', 'on')
          or
          is_state('binary_sensor.macbook_pro_google_microphone_in_use', 'on')
          or
          is_state('binary_sensor.macbook_pro_google_audio_output_in_use', 'on')
        }}
      icon: "mdi:video"
      device_class: occupancy

sensor:
  - platform: history_stats
    name: Alberto Working Hours
    entity_id: binary_sensor.alberto_working
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
