---
binary_sensor:
  - platform: workday
    country: CH
    province: ZH
  - platform: template
    sensors:
      in_working_hours:
        friendly_name: In Working Hours
        icon_template: mdi:clock
        value_template: >-
          {{
            is_state('binary_sensor.workday_sensor', 'on') and
            (
              states('sensor.time') >= (
                state_attr('input_datetime.working_hours_start', 'timestamp') |
                int |
                timestamp_custom('%H:%M', False)
              )
            ) and (
              states('sensor.time') <= (
                state_attr('input_datetime.working_hours_end', 'timestamp') |
                int |
                timestamp_custom('%H:%M', False)
              )
            )
          }}

input_datetime:
  working_hours_start:
    name: "Working Hours Start"
    has_date: false
    has_time: true
  working_hours_end:
    name: "Working Hours End"
    has_date: false
    has_time: true
