---
binary_sensor:
  - platform: workday
    country: CH
    province: ZH

template:
  - binary_sensor:
      - name: Alberto Working
        state: "{{ is_state('binary_sensor.macbook_pro_google_active', 'on') }}"
        delay_off: "00:01:00"
        icon: "mdi:briefcase"
        device_class: occupancy
      - name: Alberto in Working Meeting
        state: >-
          {{
            is_state('binary_sensor.macbook_pro_google_camera_in_use', 'on')
            or
            is_state('binary_sensor.macbook_pro_google_microphone_in_use', 'on')
            or
            is_state('binary_sensor.macbook_pro_google_audio_output_in_use', 'on')
          }}
        icon: "mdi:video"
        device_class: occupancy
      - name: Alberto Working in Office
        state: >-
          {{
            (states('sensor.macbook_pro_google_displays') | int > 1)
            and
            (
              is_state('device_tracker.albertomontes-macbookpro2', 'home')
              or
              is_state('sensor.macbook_pro_google_ssid', 'hertz')
            )
          }}
        icon: "mdi:power-plug"
        device_class: occupancy

sensor:
  - platform: history_stats
    name: Alberto Working Hours
    entity_id: binary_sensor.alberto_working
    state: "on"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
