---
binary_sensor:
  - platform: workday
    country: CH
    province: ZH

template:
  binary_sensor:
    - name: Alberto Working
      state: "{{ states('binary_sensor.albertomontes_macbookpro_active') }}"
      delay_off: "00:05:00"
      icon: "mdi:briefcase"
      device_class: occupancy
    - name: Alberto in Working Meeting
      state: >-
        {{
          is_state('binary_sensor.albertomontes_macbookpro_camera_in_use', 'on')
          and
          is_state('binary_sensor.albertomontes_macbookpro_microphone_in_use', 'on')
        }}
      delay_off: "00:02:00"
      icon: "mdi:video"
      device_class: occupancy
