---
start_white_noise:
  alias: Start White Noise For Aina
  variables:
    target_player: media_player.kids_room
    target_volume: 0.18
    # target_source: "Pure Motivation, Sleepy Koala Music 😴 Bedtime Relaxing White Noise and Calming Piano, Today’s Easy Hits"
  sequence:
    # - service: media_player.select_source
    #   data_template:
    #     entity_id: "{{ target_player }}"
    #     source: "{{ target_source }}"
    - service: media_player.volume_set
      data_template:
        entity_id: "{{ target_player }}"
        volume_level: "{{ target_volume }}"
    - service: media_player.media_play
      data_template:
        entity_id: "{{ target_player }}"

stop_white_noise:
  alias: Stop White Noise For Aina
  variables:
    target_player: media_player.kids_room
  sequence:
    - service: script.fade_volume
      data_template:
        target_player: "{{ target_player }}"
        target_volume: 0.0
        duration: 300
        curve: linear
    - service: media_player.media_pause
      data_template:
        entity_id: "{{ target_player }}"
