---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tesla-db-pv
  labels:
    app: teslamate
    component: db
  namespace: home-automation
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/disk1/data/home-automation/tesla-db
    server: 172.16.3.5
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tesla-db-pvc
  labels:
    app: teslamate
    component: db
  namespace: home-automation
spec:
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
