---
title: Home
icon: mdi:home
path: home
cards:
  - type: horizontal-stack
    cards:
      - type: markdown
        content: "# {{ states('sensor.time') }}"
      - type: markdown
        content: "## {{ states('sensor.date') }}"
  - type: glance
    entities:
      - person.judith
      - person.alberto
  - type: vertical-stack
    title: Weather
    cards:
      - type: weather-forecast
        name: Weather
        entity: weather.weather

  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.living_room_tv
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.living_room
        name: Sonos Speakers
        artwork: cover
        hide:
          power: true
          icon: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.living_room
              name: Living Room
            - entity_id: media_player.dining_room
              name: Dinning Room
            - entity_id: media_player.office
              name: Office

  - type: horizontal-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.inside_temperature
          - entity: sensor.outdoor_temperature
            name: Outside
        name: Temperature
        animate: true
        hour24: true
        decimals: 0
      - type: custom:mini-graph-card
        entities:
          - sensor.inside_humidity
          - entity: sensor.outdoor_humidity
            name: Outside
        name: Humidity
        animate: true
        hour24: true
        decimals: 0
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.living_room
          - light.dna_lamp
          - type: divider
          - light.bathroom
          - type: divider
          - light.kitchen
          - light.dining_room
          - type: divider
          - light.hallway
          - type: divider
          - light.bedroom
          - light.bed_led_strip
          - type: divider
          - light.office
          - type: divider
          - light.kid_s_room
  - type: vertical-stack
    title: Covers
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - cover.living_room
          - cover.balcony_shades
          - type: divider
          - cover.dining_room
          - type: divider
          - cover.bedroom
          - type: divider
          - cover.office
          - type: divider
          - cover.kid_s_room
  - type: vertical-stack
    title: Cleaning
    cards:
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        name: Vacuum
      - type: entities
        entities:
          - input_boolean.vacuum_clean_when_leave_home
          - input_select.vacuum_room
  - type: vertical-stack
    title: Waste
    cards:
      - type: custom:garbage-collection-card
        entity: sensor.cardboard_waste
      - type: custom:garbage-collection-card
        entity: sensor.paper_waste
  - type: horizontal-stack
    title: Scenes
    cards:
      - type: custom:button-card
        entity: scene.daylight
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.daylight
      - type: custom:button-card
        entity: scene.evening
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.evening
      - type: custom:button-card
        entity: scene.night
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.night
      - type: custom:button-card
        entity: scene.gaming
        tap_action:
          action: call-service
          service: scene.turn_on
          service_data:
            entity_id: scene.gaming
      - type: custom:button-card
        entity: lock.entrance_door
        tap_action:
          action: more-info
