---
title: Home
icon: mdi:home
path: home
cards:
  - type: horizontal-stack
    cards:
      - type: markdown
        content: "# {{ states('sensor.time') }}"
      - type: markdown
        content: "## {{ states('sensor.date') }}"
  - type: horizontal-stack
    cards:
      - type: tile
        entity: person.judith
      - type: tile
        entity: person.alberto
  - type: vertical-stack
    title: Weather
    cards:
      - type: weather-forecast
        name: Weather
        entity: weather.weather

  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.living_room_tv
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.living_room
        name: Sonos Speakers
        artwork: cover
        hide:
          power: true
          icon: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.living_room
              name: Living Room
            - entity_id: media_player.dining_room
              name: Dinning Room
            - entity_id: media_player.office
              name: Office

  - type: horizontal-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.inside_temperature
          - entity: sensor.outdoor_temperature
            name: Outside
        name: Temperature
        animate: true
        hour24: true
        decimals: 0
      - type: custom:mini-graph-card
        entities:
          - sensor.inside_humidity
          - entity: sensor.outdoor_humidity
            name: Outside
        name: Humidity
        animate: true
        hour24: true
        decimals: 0
  - type: grid
    title: Lights
    square: false
    columns: 2
    cards:
      - type: tile
        entity: light.living_room
        name: Living Room
      - type: tile
        entity: light.dna_lamp
        name: DNA Lamp
      - type: tile
        entity: light.bathroom
        name: Bathroom
      - type: tile
        entity: light.kitchen
        name: Kitchen
      - type: tile
        entity: light.dining_room
        name: Dining Room
      - type: tile
        entity: light.hallway
        name: Hallway
      - type: tile
        entity: light.bedroom
        name: Bedroom
      - type: tile
        entity: light.bed_led_strip
        name: Bed LED Strip
      - type: tile
        entity: light.office
        name: Office
      - type: tile
        entity: light.kid_s_room
        name: Kid's Room
  - type: grid
    title: Covers
    square: false
    columns: 2
    cards:
      - type: tile
        entity: cover.living_room
        features:
          - type: "cover-open-close"
      - type: tile
        entity: cover.balcony_shades
        features:
          - type: "cover-open-close"
      - type: tile
        entity: cover.dining_room
        features:
          - type: "cover-open-close"
      - type: tile
        entity: cover.bedroom
        features:
          - type: "cover-open-close"
      - type: tile
        entity: cover.office
        features:
          - type: "cover-open-close"
      - type: tile
        entity: cover.kid_s_room
        features:
          - type: "cover-open-close"
  - type: vertical-stack
    title: Cleaning
    cards:
      - type: tile
        entity: vacuum.xiaomi_vacuum_cleaner
        features:
          - type: vacuum-commands
            commands:
              - start_pause
              - stop
              - clean_spot
              - locate
              - return_home
      - type: entities
        entities:
          - input_boolean.vacuum_clean_when_leave_home
          - input_select.vacuum_room
  - type: grid
    title: Waste
    square: false
    columns: 2
    cards:
      - type: tile
        entity: sensor.cardboard_waste
      - type: tile
        entity: sensor.paper_waste
  - type: grid
    title: Scenes
    square: false
    columns: 2
    cards:
      - type: tile
        entity: scene.daylight
      - type: tile
        entity: scene.evening
      - type: tile
        entity: scene.night
  - type: grid
    title: Locks
    square: false
    columns: 2
    cards:
      - type: tile
        entity: lock.entrance_door
      # - type: tile
      #   entity: lock.street_door
