---
title: Home
icon: mdi:home
panel: false
path: home
cards:
  - type: glance
    entities:
      - person.judith
      - person.alberto
  - type: custom:weather-card
    name: Weather
    entity: weather.weather

  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.gordi_town
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.marmotilla_village
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.living_room
        name: Sonos Speakers
        artwork: cover
        hide:
          power: true
          icon: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.living_room
              name: Living Room
            - entity_id: media_player.bedroom
              name: Bedroom
            - entity_id: media_player.office
              name: Office

  - type: horizontal-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.inside_temperature
          - entity: sensor.dark_sky_temperature
            name: Outside
        name: Temperature
        animate: true
        hour24: true
        points_per_hour: 1
        decimals: 0
      - type: custom:mini-graph-card
        entities:
          - sensor.inside_humidity
          - entity: sensor.dark_sky_humidity
            name: Outside
        name: Humidity
        animate: true
        hour24: true
        points_per_hour: 1
        decimals: 0
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.living_room
          - light.sofa_led
          - light.tv_led
          - type: divider
          - light.dining_room
          - type: divider
          - light.corridor
          - type: divider
          - light.bedroom
          - light.bed_led
          - type: divider
          - light.office
  - type: vertical-stack
    title: Cleaning
    cards:
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        name: Vacuum
      - type: entities
        entities:
          - input_boolean.vacuum_clean_when_leave_home
  - type: vertical-stack
    title: Waste
    cards:
      - type: entities
        entities:
          - sensor.cardboard_waste
          - sensor.paper_waste
          - sensor.textile_waste
