---
title: Living Room
icon: mdi:sofa
panel: false
path: living_room
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.living_room_tv
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.living_room
        artwork: cover
        hide:
          power: true
          icon: true
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.living_room
          - light.sofa_led
          # - light.tv_led
          - type: divider
          - light.dining_room
  - type: horizontal-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.living_room_temperature
        name: Temperature
        animate: true
        hour24: true
        decimals: 0
      - type: custom:mini-graph-card
        entities:
          - sensor.living_room_humidity
        name: Humidity
        animate: true
        hour24: true
        decimals: 0
