---
title: Living Room
icon: mdi:sofa
path: living_room
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.living_room_tv
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.living_room
        artwork: cover
        hide:
          power: true
          icon: true
  - type: grid
    title: Lights
    square: false
    columns: 2
    cards:
      - type: tile
        entity: light.living_room
        name: Living Room
      - type: tile
        entity: light.living_room_lamp
      - type: tile
        entity: light.south_balcony
      - type: tile
        entity: light.south_balcony_floor
  - type: grid
    title: Covers
    square: false
    columns: 2
    cards:
      - type: tile
        entity: cover.living_room
        features:
          - type: "cover-open-close"
      - type: tile
        entity: cover.balcony_shades
        features:
          - type: "cover-open-close"
  - type: grid
    title: Climate
    square: false
    columns: 2
    cards:
      - type: tile
        entity: sensor.living_room_temperature
        name: Temperature
      - type: tile
        entity: sensor.living_room_humidity
        name: Humidity
  # - type: horizontal-stack
  #   title: Climate
  #   cards:
  #     - type: custom:mini-graph-card
  #       entities:
  #         - sensor.living_room_temperature
  #       name: Temperature
  #       animate: true
  #       hour24: true
  #       decimals: 0
  #     - type: custom:mini-graph-card
  #       entities:
  #         - sensor.living_room_humidity
  #       name: Humidity
  #       animate: true
  #       hour24: true
  #       decimals: 0
  - type: vertical-stack
    title: Presence
    cards:
      - type: tile
        entity: binary_sensor.living_room_occupancy
