---
title: Living Room
icon: mdi:sofa
panel: false
path: living_room
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.living_room_tv
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.living_room
        artwork: cover
        hide:
          power: true
          icon: true
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.living_room
          - light.dna_lamp
          - type: divider
          - light.south_balcony
          - light.south_balcony_floor
  - type: vertical-stack
    title: Cover
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - cover.living_room
          - type: divider
          - cover.balcony_shades
  - type: horizontal-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.living_room_temperature
        name: Temperature
        animate: true
        hour24: true
        decimals: 0
      - type: custom:mini-graph-card
        entities:
          - sensor.living_room_humidity
        name: Humidity
        animate: true
        hour24: true
        decimals: 0
  - type: vertical-stack
    title: Presence
    cards:
      - type: glance
        entities:
          - binary_sensor.living_room_occupancy
