---
title: Kitchen Dining Room
icon: mdi:silverware
path: kitchen_dining_room
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.dining_room
        artwork: cover
        hide:
          power: true
          icon: true
  - type: grid
    title: Lights
    square: false
    columns: 2
    cards:
      - type: tile
        entity: light.kitchen
      - type: tile
        entity: light.kitchen_focus
      - type: tile
        entity: light.kitchen_led_strip_ceiling
      - type: tile
        entity: light.kitchen_led_strip_floor
      - type: tile
        entity: light.dining_room
      - type: tile
        entity: light.north_balcony
  - type: vertical-stack
    title: Cover
    cards:
      - type: tile
        entity: cover.dining_room
        features:
          - type: "cover-open-close"
  - type: vertical-stack
    title: Presence
    cards:
      - type: tile
        entity: binary_sensor.dining_room_occupancy
