---
title: Bedroom
icon: mdi:bed-empty
panel: false
path: bedroom
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.bedroom_tv
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.main_bedroom
        artwork: cover
        hide:
          power: true
          icon: true
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.bedroom
          - light.bed_led_strip
          - type: divider
          - light.ensuite_bathroom
          - light.ensuite_bathroom_mirror
          - type: divider
          - light.dressing_room
  - type: vertical-stack
    title: Cover
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - cover.bedroom
  - type: horizontal-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.bedroom_temperature
        name: Temperature
        animate: true
        hour24: true
        decimals: 0
      - type: custom:mini-graph-card
        entities:
          - sensor.bedroom_humidity
        name: Humidity
        animate: true
        hour24: true
        decimals: 0
