title: Bedroom
icon: mdi:bed-empty
panel: false
path: bedroom
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.marmotilla_village
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.bedroom
        artwork: cover
        hide:
          power: true
          icon: true
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.bedroom
          - light.bed_led
  - type: vertical-stack
    title: Bed
    cards:
      - type: entities
        entities:
          - binary_sensor.alberto_in_bed
          - binary_sensor.judith_in_bed
          - binary_sensor.anyone_in_bed
          - binary_sensor.everybody_in_bed
  - type: vertical-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities: 
        - sensor.bedroom_temperature
        name: Temperature
        animate: true
        hour24: true
        decimals: 1
      - type: custom:mini-graph-card
        entities: 
        - sensor.bedroom_humidity
        name: Humidity
        animate: true
        hour24: true
        decimals: 1
      - type: custom:mini-graph-card
        entities: 
        - sensor.bedroom_pressure
        name: Pressure
        animate: true
        hour24: true
        decimals: 1
      - type: entities
        entities:
          - entity: sensor.mold_indicator_bedroom