---
title: Bedroom
icon: mdi:bed-empty
panel: false
path: bedroom
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.bedroom_tv
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.main_bedroom
        artwork: cover
        hide:
          power: true
          icon: true
      - type: entities
        show_header_toggle: false
        entities:
          - script.start_white_noise
          - script.stop_white_noise
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.bedroom
          - light.bed_led_strip
          - type: divider
          - light.ensuite_bathroom
          - light.ensuite_bathroom_mirror
          - type: divider
          - light.dressing_room
  - type: vertical-stack
    title: Cover
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - cover.bedroom
  - type: vertical-stack
    title: Climate
    cards:
      - type: humidifier
        entity: humidifier.main_bedroom
        name: Humidifier
      - type: entities
        show_header_toggle: false
        entities:
          - number.humidifier_mist_level
          - binary_sensor.humidifier_out_of_water
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.bedroom_temperature
            name: Temperature
            animate: true
            hour24: true
            decimals: 0
          - type: custom:mini-graph-card
            entities:
              - sensor.bedroom_humidity
            name: Humidity
            animate: true
            hour24: true
            decimals: 0
  - type: vertical-stack
    title: Presence
    cards:
      - type: glance
        entities:
          - binary_sensor.bedroom_occupancy
