---
title: Bedroom
icon: mdi:bed-empty
path: bedroom
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.bedroom_tv
        artwork: full-cover
      - type: custom:mini-media-player
        entity: media_player.main_bedroom
        artwork: cover
        hide:
          power: true
          icon: true
  - type: grid
    title: Lights
    square: false
    columns: 2
    cards:
      - type: tile
        entity: light.bedroom
      - type: tile
        entity: light.bed_led_strip
      - type: tile
        entity: light.ensuite_bathroom
      - type: tile
        entity: light.ensuite_bathroom_mirror
      - type: tile
        entity: light.dressing_room
  - type: vertical-stack
    title: Cover
    cards:
      - type: tile
        entity: cover.bedroom
        features:
          - type: "cover-open-close"
  - type: grid
    title: Climate
    square: false
    columns: 2
    cards:
      - type: tile
        entity: sensor.bedroom_temperature
        name: Temperature
      - type: tile
        entity: sensor.bedroom_humidity
        name: Humidity
  # - type: vertical-stack
  #   title: Climate
  #   cards:
  #     - type: horizontal-stack
  #       cards:
  #         - type: custom:mini-graph-card
  #           entities:
  #             - sensor.bedroom_temperature
  #           name: Temperature
  #           animate: true
  #           hour24: true
  #           decimals: 0
  #         - type: custom:mini-graph-card
  #           entities:
  #             - sensor.bedroom_humidity
  #           name: Humidity
  #           animate: true
  #           hour24: true
  #           decimals: 0
  - type: vertical-stack
    title: Presence
    cards:
      - type: tile
        entity: binary_sensor.bedroom_occupancy
