---
title: Kid's Room
icon: mdi:bed-outline
path: kids_room
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.kids_room
        artwork: cover
        hide:
          power: true
          icon: true
      - type: tile
        entity: switch.white_noise_music
  - type: vertical-stack
    title: Lights
    cards:
      - type: tile
        entity: light.kids_room
  - type: vertical-stack
    title: Cover
    cards:
      - type: tile
        entity: cover.kids_room
        features:
          - type: "cover-open-close"
  - type: vertical-stack
    title: Climate
    cards:
      - type: custom:mini-humidifier
        entity: humidifier.main_bedroom
        target_humidity:
          icon: "mdi:water"
          hide: false
      - type: entities
        show_header_toggle: false
        entities:
          - number.humidifier_mist_level
          - binary_sensor.humidifier_out_of_water
  - type: vertical-stack
    title: Presence
    cards:
      - type: tile
        entity: binary_sensor.kids_room_occupancy
        name: Occupancy
