---
title: Kid's Room
icon: mdi:bed-outline
path: kids_room
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.kids_room
        artwork: cover
        hide:
          power: true
          icon: true
      - type: entities
        show_header_toggle: false
        entities:
          - switch.white_noise_music
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.kid_s_room
  - type: vertical-stack
    title: Cover
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - cover.kid_s_room
  - type: vertical-stack
    title: Climate
    cards:
      - type: humidifier
        entity: humidifier.main_bedroom
        name: Humidifier
      - type: entities
        show_header_toggle: false
        entities:
          - number.humidifier_mist_level
          - binary_sensor.humidifier_out_of_water
  - type: vertical-stack
    title: Presence
    cards:
      - type: glance
        entities:
          - binary_sensor.kids_room_occupancy
