---
title: Bathrooms
icon: mdi:shower
path: bathrooms
cards:
  - type: grid
    title: Lights
    square: false
    columns: 2
    cards:
      - type: tile
        entity: light.bathroom
      - type: tile
        entity: light.bathroom_mirror
  - type: grid
    title: Climate
    square: false
    columns: 2
    cards:
      - type: tile
        entity: sensor.bathroom_temperature
        name: Temperature
      - type: tile
        entity: sensor.bathroom_humidity
        name: Humidity
  - type: grid
    title: Laundry
    square: false
    columns: 2
    cards:
      - type: tile
        entity: binary_sensor.washing_machine_running
        tap_action:
          action: navigate
          navigation_path: "/config/devices/device/647b028956fd860b6ab3835f5f5fcf42"
      - type: tile
        entity: binary_sensor.dryer_running
        tap_action:
          action: navigate
          navigation_path: "/config/devices/device/0cedba055e4825631a1b6ab8692c38b3"
