---
title: Bathrooms
icon: mdi:shower
panel: false
path: bathrooms
cards:
  - type: horizontal-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities:
          - sensor.main_bathroom_temperature
        name: Temperature
        animate: true
        hour24: true
        decimals: 0
      - type: custom:mini-graph-card
        entities:
          - sensor.main_bathroom_humidity
        name: Humidity
        animate: true
        hour24: true
        decimals: 0
