title: Bathrooms
icon: mdi:shower
panel: false
path: bathrooms
cards:
  - type: vertical-stack
    title: Climate
    cards:
      - type: custom:mini-graph-card
        entities: 
        - sensor.main_bathroom_temperature
        name: Temperature
        animate: true
        hour24: true
        decimals: 1
      - type: custom:mini-graph-card
        entities: 
        - sensor.main_bathroom_humidity
        name: Humidity
        animate: true
        hour24: true
        decimals: 1
      - type: custom:mini-graph-card
        entities: 
        - sensor.main_bathroom_pressure
        name: Pressure
        animate: true
        hour24: true
        decimals: 1