---
title: Office
icon: mdi:chair-rolling
path: office
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.office
        artwork: cover
        hide:
          power: true
          icon: true
  - type: grid
    title: Lights
    square: false
    columns: 2
    cards:
      - type: tile
        entity: light.office
      - type: tile
        entity: light.office_wall_lines
  - type: vertical-stack
    title: Cover
    cards:
      - type: tile
        entity: cover.office
        features:
          - type: "cover-open-close"
  - type: vertical-stack
    title: Climate
    cards:
      - type: custom:mini-climate
        entity: climate.office
        name: Fan
        temperature:
          round: 0
      - type: grid
        square: false
        columns: 2
        cards:
          - type: tile
            entity: sensor.office_temperature
            name: Temperature
          - type: tile
            entity: sensor.office_humidity
            name: Humidity
  - type: grid
    title: Alberto Working
    square: false
    columns: 3
    cards:
      - type: tile
        entity: binary_sensor.alberto_working
        name: Is Working?
      - type: tile
        entity: sensor.alberto_working_hours
        name: Hours
      - type: tile
        entity: binary_sensor.alberto_in_working_meeting
        name: In a Meeting
