---
title: Office
icon: mdi:chair-rolling
panel: false
path: office
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.office
        artwork: cover
        hide:
          power: true
          icon: true
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.office
  - title: Prusa MK3S
    type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: gauge
            title: Bed Temp
            entity: sensor.prusa_mk3s_actual_bed_temp
            unit_of_measurement: 째C
            min: 0
            max: 150
            severity:
              red: 120
              amber: 0
              green: 60

          - type: gauge
            title: Hot End Temp
            entity: sensor.prusa_mk3s_actual_tool0_temp
            unit_of_measurement: 째C
            min: 0
            max: 260
            severity:
              red: 225
              amber: 0
              green: 200

      - type: horizontal-stack
        cards:
          - type: gauge
            title: Bed Target
            entity: sensor.prusa_mk3s_target_bed_temp
            unit_of_measurement: 째C
            min: 0
            max: 150
            severity:
              red: 120
              amber: 0
              green: 59

          - type: gauge
            title: Hot End Target
            entity: sensor.prusa_mk3s_target_tool0_temp
            unit_of_measurement: 째C
            min: 0
            max: 260
            severity:
              red: 225
              amber: 0
              green: 199

      # - type: 'custom:bignumber-card'
      #   title: Current Job Completion Status
      #   entity: sensor.prusa_mk3s_job_percentage
      #   scale: 30px
      #   from: left
      #   min: 0
      #   max: 100
      #   severity:
      #     - value: 20
      #       style: 'var(--label-badge-red)'
      #     - value: 40
      #       style: 'var(--label-badge-yellow)'
      #     - value: 70
      #       style: 'var(--label-badge-green)'

      - type: horizontal-stack
        cards:
          - type: sensor
            name: Elapsed
            entity: sensor.prusa_mk3s_time_elapsed
            graph: none

          - type: sensor
            name: Remaining
            entity: sensor.prusa_mk3s_time_remaining
            graph: none

      - type: glance
        show_header_toggle: false
        column_width: calc(100% / 3)
        entities:
          - entity: binary_sensor.prusa_mk3s_printing
            name: Printing Status
            icon: mdi:printer-wireless
          - entity: binary_sensor.prusa_mk3s_printing_error
            name: Error State
            icon: mdi:printer-alert
          - entity: sensor.prusa_mk3s_current_state
            name: Current Status
