---
title: Office
icon: mdi:chair-rolling
path: office
cards:
  - type: vertical-stack
    title: Media
    cards:
      - type: custom:mini-media-player
        entity: media_player.office
        artwork: cover
        hide:
          power: true
          icon: true
  - type: vertical-stack
    title: Lights
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - light.office
          - light.office_wall_lines
  - type: vertical-stack
    title: Cover
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - cover.office
  - type: vertical-stack
    title: Climate
    cards:
      - type: custom:mini-climate
        entity: climate.office
        name: Fan
        temperature:
          round: 0
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - sensor.office_temperature
            name: Temperature
            animate: true
            hour24: true
            decimals: 1
          - type: custom:mini-graph-card
            entities:
              - sensor.office_humidity
            name: Humidity
            animate: true
            hour24: true
            decimals: 1
  - type: vertical-stack
    title: Alberto Working
    cards:
      - type: glance
        entities:
          - name: Is Working?
            entity: binary_sensor.alberto_working
          - name: Hours
            entity: sensor.alberto_working_hours
          - name: In a Meeting
            entity: binary_sensor.alberto_in_working_meeting
