---
path: guests
title: Guests
icon: "mdi:account-multiple-plus"
cards:
  - type: grid
    title: Guests
    square: false
    columns: 2
    cards:
      - type: tile
        entity: input_boolean.guests_visiting
      - type: tile
        entity: binary_sensor.guests_presence

  - type: vertical-stack
    title: WiFi
    cards:
      - type: picture
        image: "/local/images/wifi_qr_code.png"
      - type: markdown
        content: >-
          **WiFi**: `hertz_guest`

          **Password**: `sUYWtQs2XXIBoi1wehKl`

  - type: vertical-stack
    title: Visitors Parking
    cards:
      - type: iframe
        url: "https://app.parkon.ch/Portal/60oxch"
        aspect_ratio: "2:3"
      - type: markdown
        content: "Our car's plate: **ZH 497695**"
