---
title: Cleaning
icon: mdi:spray-bottle
path: cleaning
cards:
  - type: vertical-stack
    title: Robot
    cards:
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        name: Vacuum
  - type: grid
    title: Configuration
    square: false
    columns: 2
    cards:
      - type: tile
        entity: input_boolean.vacuum_clean_when_leave_home
        name: Clean When Leaving
      - type: tile
        entity: automation.vacuum_clean_on_monday
        name: Clean on Monday
      - type: tile
        entity: script.vacuum_to_empty_bin
        name: To Empty Bin
        icon_tap_action:
          action: call-service
          service: script.vacuum_to_empty_bin
          confirmation: true
  - type: vertical-stack
    title: Clean Room
    cards:
      - type: custom:auto-entities
        card:
          type: grid
          square: false
          columns: 2
        card_param: cards
        filter:
          include:
            - entity_id: script.vacuum_room_.*
              options:
                type: tile
                entity: this.entity_id
                icon_tap_action:
                  action: call-service
                  service: this.entity_id
                  confirmation: true
