---
title: Cleaning
icon: mdi:spray-bottle
panel: false
path: cleaning
cards:
  - type: vertical-stack
    title: Robot
    cards:
      - type: custom:xiaomi-vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        name: Vacuum
  - type: horizontal-stack
    title: Configuration
    cards:
      - type: glance
        entities:
          - entity: input_boolean.vacuum_clean_when_leave_home
            tap_action:
              action: toggle
          - entity: script.vacuum_to_empty_bin
            show_state: false
            tap_action:
              action: toggle
  - type: vertical-stack
    title: Clean Room
    cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - entity_id: script.vacuum_room_.*
