---
title: Cleaning
icon: mdi:spray-bottle
panel: false
path: cleaning
cards:
  - type: vertical-stack
    cards:
      - type: custom:vacuum-card
        entity: vacuum.xiaomi_vacuum_cleaner
        stats:
          default:
            - attribute: filter_left
              unit: hours
              subtitle: Filter
            - attribute: side_brush_left
              unit: hours
              subtitle: Side brush
            - attribute: main_brush_left
              unit: hours
              subtitle: Main brush
            - attribute: sensor_dirty_left
              unit: hours
              subtitle: Sensors
      - type: entities
        entities:
          - input_boolean.vacuum_clean_when_leave_home
          - input_select.vacuum_room
