---
title: Security
icon: mdi:shield-lock
panel: false
path: security
cards:
  - type: horizontal-stack
    title: Locks
    cards:
      - type: custom:button-card
        entity: lock.entrance_door
        tap_action:
          action: more-info
      - type: custom:button-card
        entity: lock.street_door
        tap_action:
          action: call-service
          service: lock.unlock
          service_data:
            entity_id: lock.street_door
  - type: vertical-stack
    title: Alarm
    cards:
      - type: alarm-panel
        name: House Alarm
        entity: alarm_control_panel.alarm
  - type: vertical-stack
    title: Motion Sensors
    cards:
      - type: glance
        entities:
          - binary_sensor.motion_at_home
      - type: custom:auto-entities
        card:
          type: glance
        filter:
          include:
            - entity_id: binary_sensor.*_occupancy
