---
title: Security
icon: mdi:shield-lock
path: security
cards:
  - type: grid
    title: Locks
    square: false
    columns: 2
    cards:
      - type: tile
        entity: lock.entrance_door
      - type: tile
        entity: lock.street_door
  - type: vertical-stack
    title: Alarm
    cards:
      - type: alarm-panel
        name: House Alarm
        entity: alarm_control_panel.alarm
  - type: vertical-stack
    title: Motion Sensors
    cards:
      - type: tile
        entity: binary_sensor.motion_at_home
      - type: custom:auto-entities
        card:
          type: grid
          square: false
          columns: 2
        card_param: cards
        filter:
          include:
            - entity_id: binary_sensor.*_occupancy
              options:
                type: tile
                entity: this.entity_id
