---
title: Settings
icon: mdi:cog
panel: false
path: settings
cards:
  - type: vertical-stack
    title: Search
    cards:
      - type: custom:search-card
        max_results: 10
  - type: vertical-stack
    title: Internet
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.speedtest_download
            name: Download
          - entity: sensor.speedtest_upload
            name: Upload
        name: Speed
        icon: mdi:server
        extrema: true
        animate: true
        hour24: true
        points_per_hour: 1
        decimals: 1
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.speedtest_ping
        extrema: true
        name: Ping
        icon: mdi:flash
        animate: true
        hour24: true
        points_per_hour: 1
        decimals: 1
  - type: vertical-stack
    title: Sensors Batteries
    cards:
      - type: custom:auto-entities
        card:
          type: custom:battery-state-card
        filter:
          include:
            - entity_id: sensor.*_sensor_battery
            - entity_id: sensor.*_switch_battery
  - type: vertical-stack
    title: Device Status
    cards:
      - type: custom:auto-entities
        card:
          type: entities
        filter:
          include:
            - entity_id: binary_sensor.*_status
