---
title: Settings
icon: mdi:cog
path: settings
cards:
  - type: vertical-stack
    title: Search
    cards:
      - type: custom:search-card
        max_results: 10
  - type: vertical-stack
    title: Internet
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.speedtest_download
            name: Download
          - entity: sensor.speedtest_upload
            name: Upload
        name: Speed
        icon: mdi:server
        extrema: true
        animate: true
        hour24: true
        points_per_hour: 1
        decimals: 1
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.speedtest_ping
        extrema: true
        name: Ping
        icon: mdi:flash
        animate: true
        hour24: true
        points_per_hour: 1
        decimals: 1
  - type: vertical-stack
    title: Sensors Batteries
    cards:
      - type: custom:auto-entities
        card:
          type: grid
          square: false
          columns: 2
        card_param: cards
        filter:
          include:
            - entity_id: sensor.*_battery
              options:
                type: tile
                entity: this.entity_id
  - type: vertical-stack
    title: Device Status
    cards:
      - type: custom:auto-entities
        card:
          type: grid
          square: false
          columns: 2
        card_param: cards
        filter:
          include:
            - entity_id: binary_sensor.*_status
              options:
                type: tile
                entity: this.entity_id
  - type: vertical-stack
    title: Wifi Devices Connectivity
    cards:
      - type: custom:auto-entities
        card:
          type: grid
          square: false
          columns: 2
        card_param: cards
        filter:
          include:
            - entity_id: sensor.*_wifi_signal_strength
              options:
                type: tile
                entity: this.entity_id
  - type: vertical-stack
    title: Zigbee Devices Connectivity
    cards:
      - type: custom:auto-entities
        card:
          type: grid
          square: false
          columns: 2
        card_param: cards
        filter:
          include:
            - entity_id: sensor.*_linkquality
              options:
                type: tile
                entity: this.entity_id
