---
title: Automations
icon: mdi:clock
panel: false
path: automations
cards:
  - type: vertical-stack
    title: Work
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - binary_sensor.workday_sensor
          - input_datetime.working_hours_start
          - input_datetime.working_hours_end
          - binary_sensor.in_working_hours
