---
title: Automations
icon: mdi:clock
panel: false
path: automations
cards:
  - type: vertical-stack
    title: Work
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - binary_sensor.workday_sensor
          - input_datetime.working_hours_start
          - input_datetime.working_hours_end
          - binary_sensor.in_working_hours
          - type: divider
          - automation.play_music_when_day_starts
          - automation.play_music_when_entering_home
          - automation.pause_music_when_leaving_home
          - type: divider
          - automation.notify_when_judith_leaves_work
          - automation.notify_judith_when_picked_up
          - type: divider
          - automation.pause_music_on_work_meeting
          - automation.resume_music_after_work_meeting
          - automation.notification_on_work_meeting
  - type: vertical-stack
    title: Media Players
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - automation.switch_on_sofa_light_on_media
          - automation.switch_off_sofa_light_on_media
          - type: divider
          - automation.switch_on_bed_light_on_media
          - automation.switch_off_bed_light_on_media
          - type: divider
          - automation.pause_music_on_content_in_tv
          - automation.pause_music_on_leaving_home
  - type: vertical-stack
    title: Vacuum Cleaner
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - automation.vacuum_robot_starts
          - automation.vacuum_robot_ends
          - type: divider
          - automation.started_cleaning_when_leaving
  - type: vertical-stack
    title: Notifications
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - automation.notify_leaving_basketball_practice
