---
- alias: Notify Leaving Basketball Practice
  id: notify_leaving_basketball_practice
  trigger:
    - platform: zone
      entity_id: person.alberto
      zone: zone.schule_leutschenbach
      event: leave
    - platform: zone
      entity_id: person.alberto
      zone: zone.schulhaus_doltschi
      event: leave
  condition:
    - condition: state
      entity_id: binary_sensor.someone_home
      state: 'on'
  action:
    - alias: Notify Judith
      service: notify.mobile_app_iphone_judith
      data:
        title: "Alberto just left basketball practice!"
        message: "He will be home soon."

- alias: Notify Leaving Padel
  id: notify_leaving_padel
  trigger:
    - platform: zone
      entity_id: person.alberto
      zone: zone.padel
      event: leave
  condition:
    - condition: state
      entity_id: binary_sensor.someone_home
      state: 'on'
  action:
    - alias: Notify Judith
      service: notify.mobile_app_iphone_judith
      data:
        title: "Alberto just left padel!"
        message: "He will be home soon."
