---
- alias: Notify Leaving Basketball Practice
  trigger:
    - platform: zone
      entity_id: person.alberto
      zone: zone.schule_leutschenbach
      event: leave
    - platform: zone
      entity_id: person.alberto
      zone: zone.schulhaus_doltschi
      event: leave
  condition:
    - condition: state
      entity_id: binary_sensor.someone_home
      state: 'on'
  action:
    - service: script.sonos_say
      data:
        sonos_entity: media_player.living_room
        volume: 0.5
        message: 'Alberto left training and is coming home.'
        delay: '00:00:00'
