---
- alias: Pause Music on Content in TV
  id: pause_music_on_content_in_tv
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      to: "on"
    - platform: state
      entity_id: media_player.bedroom_tv
      to: "playing"
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: media_player.living_room
          state: "playing"
        - condition: state
          entity_id: media_player.bedroom
          state: "playing"
  action:
    - service: media_player.media_pause
      data:
        entity_id: media_player.living_room
