---
- alias: Switch On Sofa Light on Media
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    to: "playing"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: time
      before: "23:59:59"
  action:
    - service: light.turn_on
      data:
        entity_id: light.sofa_led
    - service: light.turn_on
      data:
        entity_id: light.tv_led

- alias: Switch Off Sofa Light on Media
  trigger:
    platform: state
    entity_id: media_player.living_room_tv
    to: "off"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: time
      after: "21:00:00"
      before: "05:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.sofa_led
    - service: light.turn_off
      data:
        entity_id: light.tv_led

- alias: Switch On Bed Light on Media
  trigger:
    platform: state
    entity_id: media_player.bedroom_tv
    to: "playing"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: time
      before: "23:59:59"
  action:
    - service: light.turn_on
      data:
        entity_id: light.bed_led

- alias: Switch Off Bed Light on Media
  trigger:
    platform: state
    entity_id: media_player.bedroom_tv
    to: "off"
  condition:
    - condition: state
      entity_id: sun.sun
      state: "below_horizon"
    - condition: time
      after: "21:00:00"
      before: "05:00:00"
  action:
    - service: light.turn_off
      data:
        entity_id: light.bed_led

- alias: Pause Music on Content in TV
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv
      to: "playing"
    - platform: state
      entity_id: media_player.bedroom_tv
      to: "playing"
  condition:
    - condition: state
      entity_id: media_player.living_room
      state: "playing"
  action:
    - service: media_player.media_pause
      data:
        entity_id: media_player.living_room

- alias: Pause Music on Leaving Home
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_home
      to: "off"
  condition:
    - condition: state
      entity_id: media_player.office
      state: "playing"
  action:
    - service: media_player.media_pause
      data:
        entity_id: media_player.office
