---
- alias: Good Morning
  id: good_morning
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -6.0
    - platform: time
      at: "07:30:00"
  condition:
    - condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -6.0
    - condition: time
      after: "07:30:00"
  action:
    - alias: Activate Scene
      service: scene.turn_on
      target:
        entity_id: scene.daylight

- alias: Good Evening
  id: good_evening
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      # Use civil twilight threshold: https://en.wikipedia.org/wiki/Twilight.
      below: -6.0
  action:
    - alias: Activate Scene
      service: scene.turn_on
      target:
        entity_id: scene.evening
