---
- alias: Switch On Music Start Working Hours
  trigger:
    - platform: state
      entity_id: binary_sensor.in_working_hours
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.someone_home
      state: 'on'
  action:
    - service: media_player.media_play
      data:
        entity_id: media_player.office

- alias: Switch On Music Entering During Working Hours
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_home
      to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.in_working_hours
      state: 'on'
  action:
    - service: media_player.media_play
      data:
        entity_id: media_player.office

- alias: Switch Off Music Leaving During Working Hours
  trigger:
    - platform: state
      entity_id: binary_sensor.someone_home
      to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.in_working_hours
      state: 'on'
  action:
    - service: media_player.media_pause
      data:
        entity_id: media_player.office

- alias: Notify When Judith Leaves Work
  trigger:
    - platform: zone
      entity_id: person.judith
      zone: zone.universitatsspital
      event: leave
  condition:
    - condition: state
      entity_id: binary_sensor.someone_home
      state: 'on'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    service: notify.mobile_app_iphone_alberto
    data:
      title: "Judith just left work!"
      message: "She will be home soon."

- alias: Pause Music on Work Meeting
  trigger:
    platform: state
    entity_id: calendar.work_google
    to: 'on'
  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'
  action:
    - service: media_player.media_pause
      data:
        entity_id: media_player.office

- alias: Resume Music After Work Meeting
  trigger:
    platform: state
    entity_id: calendar.work_google
    to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.in_working_hours
      state: 'on'
  action:
    - service: media_player.media_play
      data:
        entity_id: media_player.office
