---
- alias: Work Start
  id: work_start
  trigger:
    - platform: state
      entity_id: binary_sensor.alberto_working
      to: "on"
  condition:
    - alias: Working Day
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    - alias: No guests at home
      condition: state
      entity_id: binary_sensor.guests_presence
      state: "off"
  action:
    - alias: Set Working Scene
      service: scene.apply
      data:
        entities:
          light.office_wall_lines: on
          media_player.office:
            state: playing
            volume_level: 0.1

- alias: Work Stop
  id: work_stop
  trigger:
    - platform: state
      entity_id: binary_sensor.alberto_working
      to: "off"
  condition:
    - alias: Working day
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
  action:
    - alias: Set Non Working Scene
      service: scene.apply
      data:
        entities:
          light.office_wall_lines: off
          media_player.office: paused

- alias: Work Pause Music on Meeting
  id: work_pause_music_on_meeting
  trigger:
    - platform: state
      entity_id: binary_sensor.alberto_in_working_meeting
      to: "on"
  action:
    - alias: Pause Music
      service: media_player.media_pause
      target:
        entity_id: media_player.office

- alias: Work Resume Music after Meeting
  id: work_resume_music_after_meeting
  trigger:
    - platform: state
      entity_id: binary_sensor.alberto_in_working_meeting
      to: "off"
  condition:
    - alias: Working
      condition: state
      entity_id: binary_sensor.alberto_working
      state: "on"
    - alias: No guests at home
      condition: state
      entity_id: binary_sensor.guests_presence
      state: "off"
  action:
    - alias: Play Music
      service: media_player.media_play
      target:
        entity_id: media_player.office

- alias: Work Close Light
  id: work_close_light
  trigger:
    - platform: state
      entity_id: binary_sensor.alberto_working
      to: "on"
    - platform: sun
      event: sunrise
  condition:
    - alias: Working
      condition: state
      entity_id: binary_sensor.alberto_working
      state: "on"
    - alias: Sun already up
      condition: state
      entity_id: sun.sun
      state: "above_horizon"
    - alias: No guests at home
      condition: state
      entity_id: binary_sensor.guests_presence
      state: "off"
  action:
    - alias: Close Light
      service: light.turn_off
      target:
        entity_id: light.office
- alias: Work Open Light
  id: work_open_light
  trigger:
    - platform: state
      entity_id: binary_sensor.alberto_working
      to: "on"
    - platform: sun
      event: sunset
  condition:
    - alias: Working
      condition: state
      entity_id: binary_sensor.alberto_working
      state: "on"
    - alias: Sun gone
      condition: state
      entity_id: sun.sun
      state: "below_horizon"
  action:
    - alias: Open Light
      service: light.turn_on
      target:
        entity_id: light.office

- alias: Work Close Cover
  id: work_close_cover
  trigger:
    - platform: state
      entity_id: binary_sensor.alberto_working
      to: "on"
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 23.0
  condition:
    # Make sure all trigger states are met.
    - alias: Working
      condition: state
      entity_id: binary_sensor.alberto_working
      state: "on"
    - alias: Sun Position
      condition: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 23.0
      above: 5.0
    # Make sure to be in the afternoon to avoid actioning in the morning.
    - alias: Afternoon
      condition: time
      after: "12:00:00"
    # Additional condition to perform it only when sunny outside.
    - alias: Sun Shining
      condition: state
      entity_id: weather.weather
      state:
        - sunny
        - partlycloudy
  action:
    - alias: Set Cover Position
      service: cover.set_cover_position
      target:
        entity_id: cover.office
      data:
        position: 30
    - alias: Set Cover Tilt
      service: cover.set_cover_tilt_position
      target:
        entity_id: cover.office
      data:
        tilt_position: 50
- alias: Work Open Cover
  id: work_Open_cover
  trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 5.0
  condition:
    - alias: Working day
      condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
  action:
    - alias: Set Cover Tilt
      service: cover.set_cover_position
      target:
        entity_id: cover.office
      data:
        position: 100
