---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ssh-public-key
  namespace: home-automation
spec:
  encryptedData:
    c6_id_rsa.pub: >-
      AgADSad5ZyqgQKBFofCH56M+E1pHsZSpzGbbfupOvkDEUgBAv43whCh5E2lvrhGHjNdKDSB/\
      5TcgPGLjgDDnUPt3wV57mCPXug640XQua9VBGFU8f4kvlIF9KfCIdnyzFCUvaa6FLqBLD65h\
      kv28Q4KlgFPRNrO4g24kdJozE2DghyIZK5svg8+tD5tnUV7s3qszBHA+KArkIDPQJsQYsLUt\
      5HaBKtlqbZp7jRI3HRc5tD9io5WD9UB8DxMAhV31G58H+o9gQQ36bULLniCUISCcuw+GlD5s\
      vtYQLSDkEsyaT2aHJCx/fBH3S1LNGgNOjOCp9o7XXcO16+YIyk4FrqA9niVDdpRhh7atBR98\
      mTubEsS4TF69DRv9HAzJ9Nx764A3iy0alecGyjiIJ8ku5J+6BafkzOeuMLGKdlOnZY48v0eN\
      Lv+bRRWFb5VLoi8S3mr6ZETD/6c2HrBI+9eoxcUo5AX4ununvPxO8DgtTC0RrU98tFCgCo1c\
      mB/89NWl6uK/PZFjx0oDZEshhjHa+QcjG4Zn5lM/YTUy01gpydcn0XCIHJ9YlTiA28Sv9/w0\
      aWZPbfhjtUH+RGOjuav9QH0NnYiTZPaKRoKQrki1NdCLx5DgQsUl/ezcjybVqnqz4aR+Fsil\
      VLs9UcLYhdxuL3tjOMNDmCQyx7A6gugV2DwMk3covt8eb6etrq6GXoMd2kMsM1gzWuladnBb\
      z7iJLfR4dwkEmxO9IneAtOAfvZkXW+cW7ONFQmuYamfnD33PSS/hVQ3CbbK8IaToMfqj0jgd\
      ry7IelFYG6V6KWwB24xdXQHm8rkvxJRFusaSXERMxP+ExldS35geGK5bWD3Rquu1x2YclXkG\
      xpqSvw7R/yaUUiCzEXwECPGBPq5y9WpB5tTTa8sTq6TcPKdi7IRRcnz6xzdbL2IvayyGLDlh\
      Y9o37bCWaCymhs0P803hWdGEpSNLyE5hQkEpnWJeosPCp/NlTcWnXRclVwuTanDS0Vyw0hpJ\
      4SISAXSfwF79mBHLVsJil0DNy7dlLZBlwBDb5YF2Zdrfi/ZFbvy+VTYAnU3b9Yok2od9zqH1\
      8utokWixsctrwL6/48Uac6o6xIdbAxSNnGrdCbgsEz+8SF509wRBnz6DpvYtDSv1WMp45iVS\
      fgh2EWyp9W2CAWee5rOKx8A5zx06q7zktsO/6fuKbZadkoeRNikkBWUiEpHEedz/TaPcJKOj\
      jmnDvMQ7HE2EdY1dDSJhCBwtWLWURrZ7lEptBCXSc7ceWqTwDrUKRrBKdLfU+zuve8twrqJo\
      +zuR6MfMjcSSYw3KWepPUeRF5t1uwg47RDTIkRzdoK7WKXJjaXh5VwraDvxt31KAstVe4Y97\
      MuCx5bVr5/PqX3oZVIF/CQIH/+kvrcVWu4Z6WJIHG2Z8SwnMyBGK58mMAKr8Nc4Z60u3sj1/\
      lm1q7gs4PBIusR4lbCilwniXCPVxHltYgClXJAZWmYAAGE4yMY0xYCaW7mY/zBeXLOp9FNHG\
      cOpgYVPcjL/mzuQb72hGtOVzEDu7IDGlLKZ8+1Cishoh9vbeddClR/tDJAae+L+t57hP7GI0\
      qIz67zxmmo1WpOZp5e8S7XUg0H6eQQPeGD/214xuoiCXSLzOLEyDL0zEyKo/hIfJoyO6cTxR\
      3q+jckc23Rp2uav7Kwi/LvEMoOx7fVgGWrkry3ffW4
  template:
    metadata:
      creationTimestamp: null
      name: ssh-public-key
      namespace: home-automation
