---
# Use this file to store secrets like usernames and passwords.
# Learn more at https://home-assistant.io/docs/configuration/secrets/
http_api_password: password

mqtt_username: username
mqtt_password: password

influxdb_token: token

octoprint_api_key: APIKEY

# ESPHome
wifi_iot_name: wifi
wifi_iot_password: password
esphome_api_password: "password"
esphome_api_encryption_key: "jcDAVxPgvLmg0yuMQgoJHZb9vhEAc9fisaob2DeV59Y="
esphome_ota_password: "password"

ap_fallback_password: password

voicerss_api_key: APIKEY

hacs_access_token: TOKEN

xiaomi_vacuum_ip: "0.0.0.0"
xiaomi_vacuum_token: "00000000000000000000000000000000"

# Dyson fan
dyson_username: "user@name.com"
dyson_password: password
dyson_office_fan_id: "000-00-000000"
dyson_office_fan_ip: "0.0.0.0"

# Sonos Speakers
sonos_bedroom_ip: "0.0.0.0"
sonos_living_room_ip: "0.0.0.0"
sonos_office_ip: "0.0.0.0"

# Living Room TV
living_room_tv_ip: "0.0.0.0"
living_room_tv_mac: "AA:AA:AA:AA:AA:AA"

alarm_code: "1234"
