---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-pv
  labels:
    app: home-assistant
    component: core
  namespace: home-automation
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/disk1/data/home-automation/hass
    server: 172.16.3.5
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-assistant-pvc
  labels:
    app: home-assistant
    component: core
  namespace: home-automation
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
