apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
    component: db
  namespace: home-automation
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: influxdb
    component: db
