---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
    component: db
  namespace: home-automation
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8086
      protocol: TCP
      targetPort: 8086
  selector:
    app: influxdb
    component: db
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: influxdb
  labels:
    app: influxdb
    component: db
  namespace: home-automation
spec:
  entryPoints:
    - websecure
  routes:
    - match: "Host(`influxdb.hass.c6.montesg.xyz`)"
      kind: Rule
      services:
        - kind: Service
          name: influxdb
          namespace: home-automation
          passHostHeader: true
          port: 8086
  tls:
    certResolver: le
    options:
      name: mutual-auth
      namespace: traefik
