---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Sweet Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.415606
  longitude: 8.530288
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 408
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here:
  # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich
  # Customization file
  customize: !include customize.yaml
  # Split config in multiple files
  packages: !include_dir_named packages
  # Auth providers
  auth_providers:
    - type: homeassistant

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Lovelace UI
lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8  # Cluster Network where Traefik proxy is running.

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
  ignore:
    - sonos
    - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - device_tracker
      - person

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone: !include zones.yaml

# Recorder
recorder:
  db_url: postgresql://postgresadmin:gfdble34bu23g4y4fd@postgres/homeassistant
  purge_keep_days: 730

# InfluxDB
influxdb:
  host: influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb_username
  password: !secret influxdb_password
  include:
    domains:
      - sensor
      - light
      - binary_sensor

# Text to speech
tts:
  - platform: voicerss
    api_key: !secret voicerss_api_key
  - platform: google_translate

# Cloud
cloud:

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include scripts.yaml

# Apple HomeKit
homekit:
  name: Home Assistant
  entity_config: !include assistants/homekit.yaml
  filter:
    exclude_domains:
      - automation
    exclude_entity_globs:
      - device_tracker.*
      - sensor.dark_sky*
      - sensor.prusa_mk3s_*
      - sensor.tesla_*
      - sensor.outside_*
      - binary_sensor.prusa_mk3s_*
      - input_boolean.zigbee2mqtt_*
      - script.zigbee2mqtt_*
      - switch.zigbee2mqtt_*
      - switch.energy_meter_*
      - switch.office_fan_*
      - binary_sensor.albertomontes_macbookpro_*
    exclude_entities:
      - sensor.inside_temperature
      - script.sonos_say
      - script.vacuum_dispatch
      - media_player.all_tvs
      - binary_sensor.in_working_hours
      - binary_sensor.workday_sensor
      - binary_sensor.bedroom_repeater_update_available
      - binary_sensor.updater
      - light.dining_table

# Google Home
google_assistant:
  project_id: home-assistant-5435b
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - switch
    - light

# Home Assistant mobile app
mobile_app:

ios:

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:code-braces
    url: ///config.hass.c6.montesg.xyz/
  zigbee2mqttassistant:
    title: Zigbee2MQTT Assistant
    icon: mdi:router-wireless
    url: ///zigbee2mqtt.hass.c6.montesg.xyz/
  esphome:
    title: ESPHome
    icon: mdi:chip
    url: ///esphome.hass.c6.montesg.xyz/

mqtt:
  broker: mqtt
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: false
  # Required for zigbee2mqtt
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"

logger:
  default: info
  logs:
    homeassistant.components.http: warn
    homeassistant.components.device_tracker.nmap_tracker: warn
    homeassistant.components.automation.update_tesla_location: error
    pyhap.hap_server: warn
    hole: warn
    opensensemap_api: warn
    googleapiclient.discovery: warn

# System Health
system_health:

hacs:
  token: !secret hacs_access_token

google:
  client_id: !secret google_calendar_client_id
  client_secret: !secret google_calendar_client_secret
