---
homeassistant:
  # Name of the location where Home Assistant is running
  name: Sweet Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.421247255908625
  longitude: 8.562337074545214
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 408
  # Setup for our home location.
  country: CH
  time_zone: Europe/Zurich
  unit_system: metric
  currency: CHF
  language: en
  # Customization file
  customize: !include customize.yaml
  # Split config in multiple files
  packages: !include_dir_named packages
  # Auth providers
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24

homeassistant_alerts:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes

# Enables configuration UI
config:

# Lovelace UI
lovelace:
  mode: yaml
  resources: !include lovelace/resources/resources.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    # Cluster Network where Traefik proxy is running.
    - 10.0.0.0/8

# Discover some devices automatically
discovery:
  ignore:
    - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - binary_sensor
      - device_tracker
      - person

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

zone: !include zones.yaml

# Recorder
recorder:
  db_url: postgresql://hass:gfdble34bu23g4y4fd@postgres/homeassistant
  purge_keep_days: 30

# InfluxDB
influxdb:
  host: influxdb
  port: 8086
  api_version: 2
  ssl: false
  token: !secret influxdb_token
  organization: "6b9b9e3d4e053f28"
  bucket: Home Assistant
  tags:
    source: Hass
    location: Dufaux-Strasse
  tags_attributes:
    - friendly_name
  default_measurement: units
  include:
    domains:
      - sensor
      - light
      - binary_sensor
      - device_tracker
      - cover
      - sun
      - switch
      - climate
      - fan
      - weather

# Text to speech
tts:
  - platform: voicerss
    api_key: !secret voicerss_api_key
  - platform: google_translate

# Cloud
cloud:

group: !include groups.yaml
automation: !include_dir_merge_list automation
script: !include_dir_merge_named scripts

# Apple HomeKit
homekit:
  - name: Home Assistant
    entity_config: !include assistants/homekit.yaml
    filter:
      include_entities: !include_dir_merge_list ./homekit
  - name: Living Room TV
    port: 21065
    mode: accessory
    filter:
      include_entities:
        - media_player.living_room_tv

# Google Home
google_assistant:
  project_id: home-assistant-5435b
  service_account: !include service_account.json
  report_state: true
  exposed_domains:
    - switch
    - light

# Home Assistant mobile app
mobile_app:

panel_iframe:
  zigbee2mqttassistant:
    title: Zigbee2MQTT Assistant
    icon: mdi:router-wireless
    url: ///zigbee2mqtt.hass.c6.montesg.xyz/
  esphome:
    title: ESPHome
    icon: mdi:chip
    url: ///esphome.hass.c6.montesg.xyz/

panel_custom:
  - name: Automations
    sidebar_title: Automations
    sidebar_icon: mdi:cog-transfer
    js_url: /api/hassio/app/entrypoint.js
    url_path: config/automation/dashboard
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator
  - name: Devices
    sidebar_title: Devices
    sidebar_icon: mdi:devices
    js_url: /api/hassio/app/entrypoint.js
    url_path: config/devices/dashboard
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

logger:
  default: info
  logs:
    homeassistant.components.http: warn
    homeassistant.components.device_tracker.nmap_tracker: warn
    homeassistant.components.automation.update_tesla_location: error
    pyhap.hap_server: warn
    hole: warn
    opensensemap_api: warn
    googleapiclient.discovery: warn

# System Health
system_health:

wake_on_lan:

prometheus:

energy:

media_source:
