---
light.bed_led:
  friendly_name: Bed LED
  homebridge_name: Llit LED
light.bedroom:
  homebridge_name: Bedroom Light
light.corridor:
  homebridge_name: Corridor Light
light.dinning_room:
  homebridge_name: Dinning Room Light
light.living_room:
  homebridge_name: Living Room Light
light.office:
  homebridge_name: Office Light
light.sofa_led:
  friendly_name: Sofa LED
  homebridge_name: Sofa LED
light.tv_led:
  friendly_name: TV LED
  homebridge_name: TV LED

media_player.living_room:
  friendly_name: Sonos Living Room
media_player.bedroom:
  friendly_name: Sonos Bedroom
media_player.office:
  friendly_name: Sonos Office

binary_sensor.workday_sensor:
  homebridge_hidden: true
binary_sensor.in_working_hours:
  homebridge_hidden: true

fan.office:
  friendly_name: Office Fan
  homebridge_name: Office Fan

sensor.inside_temperature:
  homebridge_hidden: true
sensor.inside_humidity:
  homebridge_hidden: true

device_tracker.iphone_alberto_bt:
  friendly_name: iPhone Alberto BT
device_tracker.apple_watch_alberto_bt:
  friendly_name: Apple Watch Alberto BT
device_tracker.iphone_judith_bt:
  friendly_name: iPhone Judith BT
device_tracker.apple_watch_judith_bt:
  friendly_name: Apple Watch Judith BT
