
light.sofa_led:
  friendly_name: Sofa LED
  homebridge_name: Sofa LED
  
light.tv_led:
  friendly_name: TV LED
  homebridge_name: TV LED
  
light.bed_led:
  friendly_name: Bed LED
  homebridge_name: Llit LED
  
light.bedroom:
  homebridge_name: Bedroom Light

light.dinning_room:
  homebridge_name: Dinning Room Light

# light.mqtt_json_light:
#   friendly_name: Dinner Table Light

group.all_automations:
  friendly_name: 'All Automations'
  
  hidden: True
  homebridge_hidden: true
  
device_tracker.f099b636e2cf:
  friendly_name: iPhone Alberto
  homebridge_hidden: True
  
device_tracker.c8_3c_85_38_ca_52:
  friendly_name: iPhone Judith
  homebridge_hidden: True
  
group.zigbee_group:
  homebridge_hidden: True
  
media_player.living_room:
  friendly_name: Sonos Living Room
  
media_player.bedroom:
  friendly_name: Sonos Bedroom
  
sensor.cardboard_waste:
  icon: "mdi:package-variant"
  
sensor.paper_waste:
  icon: "mdi:file"
  
sensor.textile_waste:
  icon: "mdi:tshirt-crew"