---
light.bed_led:
  friendly_name: Bed LED
  homebridge_name: Llit LED
light.bedroom:
  homebridge_name: Bedroom Light
light.corridor:
  homebridge_name: Corridor Light
light.dinning_room:
  homebridge_name: Dinning Room Light
light.living_room:
  homebridge_name: Living Room Light
light.office:
  homebridge_name: Office Light

media_player.living_room:
  friendly_name: Sonos Living Room
  homebridge_name: Living Room Sonos
media_player.bedroom:
  friendly_name: Sonos Bedroom
  homebridge_name: Bedroom Sonos
media_player.office:
  friendly_name: Sonos Office
  homebridge_name: Office Sonos

fan.office:
  friendly_name: Office Fan
  homebridge_name: Office Fan

climate.office:
  friendly_name: Office Climate
  homebridge_name: Office Climate
