---
sonos_say:
  alias: "Sonos TTS Script"
  sequence:
    - alias: Store Sonos Snapshot
      service: sonos.snapshot
      data_template:
        entity_id: "{{ sonos_entity }}"
    - alias: Unjoin speaker
      service: sonos.unjoin
      data_template:
        entity_id: "{{ sonos_entity }}"
    - alias: Set Volume
      service: media_player.volume_set
      data_template:
        entity_id: "{{ sonos_entity }}"
        volume_level: "{{ volume }}"
    - alias: Play Text
      service: tts.google_translate_say
      data_template:
        entity_id: "{{ sonos_entity }}"
        message: "{{ message }}"
    - alias: Wait
      delay: "{{ delay }}"
    - alias: Restore Sonos Snapshot
      service: sonos.restore
      data_template:
        entity_id: "{{ sonos_entity }}"

sonos_play:
  alias: "Sonos Play File"
  sequence:
    - alias: Store Sonos Snapshot
      service: sonos.snapshot
      data_template:
        entity_id: "{{ sonos_entity }}"
    - alias: Unjoin speaker
      service: sonos.unjoin
      data_template:
        entity_id: "{{ sonos_entity }}"
    - alias: Set Volume
      service: media_player.volume_set
      data_template:
        entity_id: "{{ sonos_entity }}"
        volume_level: "{{ volume }}"
    - alias: Play Content
      service: media_player.play_media
      data_template:
        entity_id: "{{ sonos_entity }}"
        media_content_id: "https://hass.c6.montesg.xyz/local/sounds/done_for_you.mp3"
        media_content_type: music
    - alias: Wait
      delay: "{{ delay }}"
    - alias: Restore Sonos Snapshot
      service: sonos.restore
      data_template:
        entity_id: "{{ sonos_entity }}"


vacuum_kitchen:
  alias: "Vacuum Kitchen"
  sequence:
    - service: xiaomi_miio.vacuum_clean_segment
      data_template:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        segments: [21]
vacuum_sofa_area:
  alias: "Vacuum Sofa Area"
  sequence:
    - service: xiaomi_miio.vacuum_clean_segment
      data_template:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        segments: [17]
vacuum_bedroom:
  alias: "Vacuum Bedrom"
  sequence:
    - service: xiaomi_miio.vacuum_clean_segment
      data_template:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        segments: [16]
vacuum_corridor:
  alias: "Vacuum Corridor"
  sequence:
    - service: xiaomi_miio.vacuum_clean_segment
      data_template:
        entity_id: vacuum.xiaomi_vacuum_cleaner
        segments: [19]
vacuum_dispatch:
  alias: "Vacuum Dispatch"
  sequence:
    - service: script.turn_on
      data_template:
        entity_id: >-
          {% if room|lower in ("kitchen", "the kitchen") %}
            script.vacuum_kitchen
          {% elif room|lower in ("sofa area", "the sofa area") %}
            script.vacuum_sofa_area
          {% elif room|lower in ("bedroom", "the bedroom") %}
            script.vacuum_bedroom
          {% elif room|lower in ("corridor", "the corridor") %}
            script.vacuum_kitchen
          {% endif %}
