esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${friendly_name} Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
    internal: true
  - platform: adc
    id: temp_analog_reading
    pin: A0
    internal: true

status_led:
  pin:
    number: GPIO0
    inverted: yes

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"
