esphome:
  name: ${name}
  platform: ESP8266
  board: esp01_1m
  comment: "Shelly 2.5"

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: ${friendly_name} Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          # - switch.turn_off: relay_1
          # - switch.turn_off: relay_2
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: Message from ${friendly_name}
              data_template:
                message: Switch reached critical temperature ${max_temp}°C
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
    internal: true
  - platform: adc
    id: temp_analog_reading
    pin: A0
    update_interval: 10s
    internal: true

binary_sensor:
  - platform: gpio
    pin: GPIO16
    name: "ade7953 IRQ pin"
    internal: true

status_led:
  pin:
    number: GPIO0
    inverted: yes

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"
