---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
    component: db
  namespace: home-automation
data:
  POSTGRES_DB: homeassistant
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: gfdble34bu23g4y4fd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
    component: db
  namespace: home-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      component: db
  template:
    metadata:
      labels:
        app: postgres
        component: db
      namespace: home-automation
    spec:
      containers:
        - name: postgres
          image: postgres:11.7-alpine
          imagePullPolicy: Always
          ports:
            - name: db
              containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -h localhost -U postgresadmin -d homeassistant
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pvc
      nodeSelector:
        beta.kubernetes.io/arch: arm64
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    component: db
  namespace: home-automation
spec:
  type: ClusterIP
  ports:
    - name: db
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
    component: db
