---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  labels:
    app: postgres
    component: db
  namespace: home-automation
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/disk1/data/home-automation/db
    server: 172.16.3.5
  persistentVolumeReclaimPolicy: Retain
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pvc
  labels:
    app: postgress
    component: db
  namespace: home-automation
spec:
  volumeMode: Filesystem
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
