sensor:
  - platform: ade7953
    irq_pin: GPIO16 # Prevent overheating by setting this
    voltage:
      name: ${friendly_name} Voltage
    # On the Shelly 2.5 channels are mixed ch1=B ch2=A
    current_a:
      name: ${friendly_name_2} Current
    current_b:
      name: ${friendly_name_1} Current
    active_power_a:
      name: ${friendly_name_2} Active Power
      id: power_channel_2
      # active_power_a is normal, so don't multiply by -1
      filters:
        - multiply: 1
    active_power_b:
      name: ${friendly_name_1} Active Power
      id: power_channel_1
      # active_power_b is inverted, so multiply by -1
      filters:
        - multiply: -1
    update_interval: 10s
  - platform: total_daily_energy
    name: ${friendly_name_1} Energy
    power_id: power_channel_1
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
  - platform: total_daily_energy
    name: ${friendly_name_2} Energy
    power_id: power_channel_2
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    disabled_by_default: true

# output:
#   - platform: gpio
#     pin: GPIO4
#     id: relay_1
#   - platform: gpio
#     pin: GPIO15
#     id: relay_2

switch:
  - platform: gpio
    id: relay_1
    name: ${friendly_name_1}
    pin: GPIO4
    icon: "mdi:electric-switch"
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    id: relay_2
    name: ${friendly_name_2}
    pin: GPIO15
    icon: "mdi:electric-switch"
    restore_mode: RESTORE_DEFAULT_ON
    disabled_by_default: true
# light:
#   - platform: binary
#     name: ${friendly_name_1}
#     output: relay_1
#     id: light_1

#   - platform: binary
#     name: ${friendly_name_2}
#     output: relay_2
#     id: light_2
