---
# Common configuration for all ESPHome devices to setup the device and its
# connection to Home Assistant.

wifi:
  ssid: !secret wifi_iot_name
  password: !secret wifi_iot_password

  manual_ip:
    static_ip: ${device_ip}
    gateway: 10.4.0.1
    subnet: 255.255.0.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

ota:
  password: !secret esphome_ota_password

api:
  password: !secret esphome_api_password
  encryption:
    key: !secret esphome_api_encryption_key

web_server:
  port: 80

prometheus:

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${friendly_name} Uptime

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

time:
  - platform: homeassistant
    id: homeassistant_time
