---
esphome:
  name: ${name}-switch
  comment: ${upper_device_name} Switch
  platform: ESP8266
  board: esp01_1m
  build_path: /build/${device_name}_switch

wifi:
  ssid: !secret wifi_iot_name
  password: !secret wifi_iot_password

  manual_ip:
    static_ip: ${device_ip}
    gateway: 10.4.0.1
    subnet: 255.255.0.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${upper_device_name} Switch Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

ota:
  password: !secret esphome_ota_password

api:
  password: !secret esphome_api_password
  encryption:
    key: !secret esphome_api_encryption_key

web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: ${upper_device_name} Switch WiFi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${upper_device_name} Switch Uptime

binary_sensor:
  # the 7 lines below define the reset button
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true # hides reset switch from HomeAssistant
    filters:
      - invert:
      - delayed_off: 10ms
    # the 3 lines below toggle the main relay on press of reset button
    on_press:
      - light.toggle:
          id: light_id

  # the 13 lines below toggle the main relay on command
  - platform: gpio
    name: relay_toggle
    internal: true # hides relay toggle from HomeAssistant
    pin: GPIO04
    id: gpio_light_id
    on_press:
      then:
        - light.toggle:
            id: light_id
    on_release:
      then:
        - light.toggle:
            id: light_id

  # the 2 lines below create a status entity in HomeAssistant.
  - platform: status
    name: ${upper_device_name} Switch Status

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  # Control the main relay
  - platform: gpio
    pin: GPIO12
    id: main_light_relay
  # Control the Blue LED
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
  # the 4 lines below define the main relay as a light
  - platform: binary
    name: ${upper_device_name}
    output: main_light_relay
    id: light_id
  # the 4 lines below define the Blue LED light on Sonoff Mini
  - platform: monochromatic
    name: ${upper_device_name} Switch Blue LED
    output: blue_led
    internal: true # hides the Blue LED from Homeassistant

switch:
  - platform: restart
    name: "${upper_device_name} Switch Restart"
    icon: "mdi:restart"
