---
esphome:
  name: ${device_name}_switch
  platform: ESP8266
  board: esp01_1m
  build_path: /build/${device_name}_switch

wifi:
  ssid: !secret wifi_iot_name
  password: !secret wifi_iot_password

  manual_ip:
    static_ip: $device_ip
    gateway: 10.4.0.1
    subnet: 255.255.0.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$upper_device_name Switch Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

ota:

web_server:
  port: 80

mqtt:
  broker: 10.6.8.3
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: "switches/${device_name}"

status_led:
  pin:
    number: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle:
          id: relay_1

  - platform: gpio
    name: "${upper_device_name} Switch"
    pin: GPIO04
    id: switch_1
    on_press:
      then:
        - switch.turn_on:
            id: relay_1
    on_release:
      then:
        - switch.turn_off:
            id: relay_1

switch:
  - platform: gpio
    name: "${upper_device_name} Light"
    icon: "mdi:lightbulb_outline"
    pin: GPIO12
    id: relay_1
    restore_mode: restore_default_off
