---
substitutions:
  name: balcony-shades
  device_name: Balcony Shades
  friendly_name: Balcony Shades
  device_ip: 10.4.2.41
  max_temp: "85.0"

# Alternative firmware to allow OTA. The firmware for this device easily takes
# more space than half the ROM in the device (1MiB) which makes impossible
# directly OTA update. For that reason, uncomment after this comment to generate
# a minimal version that would only allow for OTA.

packages:
  device: !include templates/devices/shelly_25.yaml
  common: !include templates/common.yaml
  cover: !include templates/cover/shelly_25.yaml
