---
esphome:
  name: bed_presence_sensor
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_name
  password: !secret wifi_password

  manual_ip:
    static_ip: 172.16.4.10
    gateway: 172.16.0.1
    subnet: 255.255.0.0
    dns1: 8.8.8.8
    dns2: 8.8.4.4

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bed Presence Fallback Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

ota:

web_server:
  port: 80

mqtt:
  broker: 172.16.8.3
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: presence/main_bed

# Setting up the pressure mats
esp32_touch:
# Delete this after you are done with the setup process
#   setup_mode: true
#   iir_filter: 10ms


binary_sensor:
  - platform: esp32_touch
    name: "Top Right"
    pin: GPIO12
    threshold: 3
    id: top_right
  - platform: esp32_touch
    name: "Bottom Right"
    pin: GPIO13
    threshold: 4
    id: bottom_right
  - platform: esp32_touch
    name: "Top Left"
    pin: GPIO14
    threshold: 6
    id: top_left
  - platform: esp32_touch
    name: "Bottom Left"
    pin: GPIO15
    threshold: 6
    id: bottom_left
  - platform: template
    name: "Alberto in Bed"
    id: alberto_in_bed
    lambda: |-
      return id(top_right).state || id(bottom_right).state;
  - platform: template
    name: "Judith in Bed"
    id: judith_in_bed
    lambda: |-
      return id(top_left).state || id(bottom_left).state;
  - platform: template
    name: "Anyone in Bed"
    id: anyone_in_bed
    lambda: |-
      return id(alberto_in_bed).state || id(judith_in_bed).state;
  - platform: template
    name: "Everybody in Bed"
    id: everybody_in_bed
    lambda: |-
      return id(alberto_in_bed).state && id(judith_in_bed).state;
