---
substitutions:
  name: "bed-led-strip"
  device_name: Bed LED Strip
  friendly_name: Bed LED Strip
  device_ip: "10.4.2.21"

esphome:
  name: "${name}"
  platform: ESP8266
  board: esp8285

packages:
  common: !include templates/common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: led_light
      - timing:
          - ON for at least 4s
        then:
          - button.press: restart_button

button:
  - platform: restart
    id: restart_button
    name: "${friendly_name} Restart"
  - platform: template
    id: identify_button
    name: "${friendly_name} Identification Blink"
    # TODO: use system when supported.
    entity_category: config
    on_press:
      then:
        - script.execute: identification_blink

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO14

light:
  - platform: rgb
    name: "${friendly_name}"
    id: led_light
    icon: mdi:led-strip-variant
    red: red_output
    green: green_output
    blue: blue_output

script:
  - id: identification_blink
    then:
      - repeat:
          count: 3
          then:
            - light.toggle: led_light
            - delay: 1s
            - light.toggle: led_light
            - delay: 1s
