substitutions:
  name: "bed-led-strip"
  friendly_name: "Bed LED Strip"
  device_ip: "10.4.2.21"

esphome:
  name: "${name}"
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_iot_name
  password: !secret wifi_iot_password

  manual_ip:
    static_ip: ${device_ip}
    gateway: 10.4.0.1
    subnet: 255.255.0.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${friendly_name} Switch Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

ota:
  password: !secret esphome_ota_password

api:
  password: !secret esphome_api_password
  encryption:
    key: !secret esphome_api_encryption_key

web_server:
  port: 80

prometheus:

sensor:
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: ${friendly_name} Uptime

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

  - platform: gpio
    pin:
      number: 0
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"
    disabled_by_default: true
    on_multi_click:
      - timing:
          - ON for at most 1s
          - OFF for at least 0.2s
        then:
          - light.toggle: light1
      - timing:
          - ON for at least 4s
        then:
          - switch.turn_on: restart_switch

switch:
  - platform: restart
    id: restart_switch
    name: "${friendly_name} Restart"

output:
  - platform: esp8266_pwm
    id: red_output
    pin: GPIO12
  - platform: esp8266_pwm
    id: blue_output
    pin: GPIO4
  - platform: esp8266_pwm
    id: green_output
    pin: GPIO14

light:
  - platform: rgb
    name: "${friendly_name}"
    id: light1
    red: red_output
    green: green_output
    blue: blue_output
