---
esphome:
  name: corridor_switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_iot_name
  password: !secret wifi_iot_password

  manual_ip:
    static_ip: 10.4.2.10
    gateway: 10.4.0.1
    subnet: 255.255.0.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8


  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Corridor Switch Fallback Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

ota:

web_server:
  port: 80

mqtt:
  broker: 172.16.8.3
  username: !secret mqtt_username
  password: !secret mqtt_password
  topic_prefix: switches/corridor

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - switch.toggle: relay_1

switch:
  - platform: gpio
    name: "Corridor Light"
    icon: "mdi:lightbulb_outline"
    pin: GPIO12
    id: relay_1
    restore_mode: restore_default_off
    on_turn_on:
      then:
        - delay: 0.5s
        - switch.turn_off: relay_1
