---
esphome:
  name: corridor-switch
  comment: Corridor Switch
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_iot_name
  password: !secret wifi_iot_password

  manual_ip:
    static_ip: 10.4.2.10
    gateway: 10.4.0.1
    subnet: 255.255.0.0
    dns1: 1.1.1.1
    dns2: 8.8.8.8

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Corridor Switch Fallback Hotspot"
    password: !secret ap_fallback_password

captive_portal:

# Enable logging
logger:

ota:
  password: !secret esphome_ota_password

api:
  password: !secret esphome_api_password
  encryption:
    key: !secret esphome_api_encryption_key

web_server:
  port: 80

prometheus:

sensor:
  - platform: wifi_signal
    name: Corridor Switch Wifi Signal Strength
    update_interval: 60s
  - platform: uptime
    name: Corridor Switch Uptime

binary_sensor:
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true
    filters:
      - invert:
      - delayed_off: 10ms
    on_press:
      - light.toggle:
          id: light_id

status_led:
  pin:
    number: GPIO13
    inverted: true

output:
  - platform: gpio
    pin: GPIO12
    id: main_light_relay

light:
  - platform: binary
    name: "Corridor"
    output: main_light_relay
    id: light_id
    restore_mode: restore_default_off
    on_turn_on:
      then:
        - delay: 0.5s
        - light.turn_off: light_id

switch:
  - platform: restart
    name: "Corridor Switch Restart"
    id: restart_switch
    icon: "mdi:restart"
