---
substitutions:
  name: office-switch
  friendly_name: Office Switch
  device_ip: 10.4.2.53

packages:
  device: !include templates/devices/shelly_i3.yaml
  common: !include templates/common.yaml

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT
    name: ${friendly_name} Switch 1
    id: sensorid1
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT
    name: ${friendly_name} Switch 2
    id: sensorid2
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    pin:
      number: GPIO14
      mode: INPUT
    name: ${friendly_name} Switch 3
    id: sensorid3
    filters:
      - delayed_on_off: 50ms
