---
substitutions:
  name: washmachine
  friendly_name: Washmachine Switch
  device_ip: 10.4.2.52
  friendly_name_1: Washmachine
  friendly_name_2: Undefined
  max_temp: "85.0"

packages:
  device: !include templates/devices/shelly_25.yaml
  common: !include templates/common.yaml
  light: !include templates/light/shelly_25.yaml
