---
global:
  instanceName: living_room
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
homeAssistant:
  sendMqttRoom: true
  mqttUrl: mqtt://mqtt:1883
  mqttOptions:
    username: mosquitto
    password: 6hwxKrRnWT4MP64MoNrF

bluetoothLowEnergy:
  timeout: 60
  allowlist:
    - "2BFEEB0F-ECB6-4C44-AFF3-CDCA9BC905A0"
