---
# This is a basic workflow to help you get started with Actions

name: Home Assistant CI

# Controls when the action will run. Triggers the workflow on push or pull
# request events but only for the master branch
on:
  push:
  pull_request:
  schedule:
    - cron: 0 12 * * *

jobs:
  # Check Yaml config files
  yamllint:
    name: 🧹 yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@master
      - name: 🚀 YAML Lint Action
        uses: actionshub/yamllint@v1.0.0

  remarklint:
    name: 🧹 remarklint
    runs-on: ubuntu-18.04
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v1
      - name: 🚀 Running Remark lint
        uses: "docker://pipelinecomponents/remark-lint:latest"
        continue-on-error: true
        with:
          # yamllint disable rule:line-length
          args: "remark --no-stdout --color --frail --use preset-lint-recommended ."

  home-assistant:
    name: "Home Assistant Core ${{ matrix.version }} Configuration Check"
    needs: [yamllint]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["stable", "beta", "dev"]
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v2
      - name: Copy stub files into configuration folder
        run: cp -R ./config/.stubs/* ./config/
      - name: 🚀 Run Home Assistant Configuration Check
        uses: frenck/action-home-assistant@v1.0.0
        with:
          path: "./config"
          version: "${{ matrix.version }}"

  esphome:
    name: "ESPHome"
    runs-on: ubuntu-latest
    needs: [yamllint]
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install esphome
          pip list
          esphome version
      - name: Copy stub files into configuration folder
        run: cp -R ./config/.stubs/* ./config/
      - name: Run esphome on all files
        # yamllint disable rule:line-length
        run: |
          for file in $(find ./config/esphome -type f -name "*.yaml" -not -name "secrets.yaml" -not -path "*/templates/*"); do esphome "${file}" config; done

  kubernetes_deployments:
    name: 🧹 kubeval
    runs-on: ubuntu-latest
    steps:
      - name: Run KubeEval
        uses: stefanprodan/kube-tools@v1
        with:
          # yamllint disable rule:line-length
          command: |
            echo "Run kubeval"
            kubeval --skip-kinds SealedSecret,IngressRoute,IngressRouteTCP ./deployment/**/*.yaml
