---
homeassistant: false
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: "mqtt://mqtt:1883"
  user: "!secret mqtt_username"
  password: "!secret mqtt_password"
  version: 5
serial:
  port: /dev/ttyUSB0
advanced:
  # Needed by zig-a-zig-ah!
  rtscts: false
  last_seen: epoch
  elapsed: true
  report: true
  pan_id: 6755
  network_key: "!secret network_key"
  ikea_ota_use_test_url: true
  # Check for Trafdri LEDs that act as routers for availability.
  availability_timeout: 60

device_options:
  retain: true
  qos: 1

frontend:
  port: 8080

devices: devices.yaml
groups: groups.yaml
