---
"0x00158d0002b546af":
  friendly_name: living_room_sensor
  temperature_precision: 1
  humidity_precision: 1
  pressure_precision: 1
  retain: true
  debounce: 1
  homeassistant:
    device:
      name: Living Room Sensor
    temperature:
      name: Living Room Temperature
    humidity:
      name: Living Room Humidity
    pressure:
      name: Living Room Pressure
    battery:
      name: Living Room Sensor Battery
"0x00158d00036bd864":
  friendly_name: bathroom_sensor
  temperature_precision: 1
  humidity_precision: 1
  pressure_precision: 1
  retain: true
  debounce: 1
  homeassistant:
    device:
      name: Bathroom Sensor
    temperature:
      name: Bathroom Temperature
    humidity:
      name: Bathroom Humidity
    pressure:
      name: Bathroom Pressure
    battery:
      name: Bathroom Sensor Battery
"0x00158d0002b54dce":
  friendly_name: bedroom_sensor
  temperature_precision: 1
  humidity_precision: 1
  pressure_precision: 1
  retain: true
  debounce: 1
  homeassistant:
    device:
      name: Bedroom Sensor
    temperature:
      name: Bedroom Temperature
    humidity:
      name: Bedroom Humidity
    pressure:
      name: Bedroom Pressure
    battery:
      name: Bedroom Sensor Battery
"0x00158d00036bd476":
  friendly_name: south_balcony_sensor
  temperature_precision: 1
  humidity_precision: 1
  pressure_precision: 1
  retain: true
  debounce: 1
  homeassistant:
    device:
      name: South Balcony Sensor
    temperature:
      name: Outdoor Temperature
    humidity:
      name: Outdoor Humidity
    pressure:
      name: Outdoor Pressure
    battery:
      name: South Balcony Sensor Battery

"0x000d6ffffe46f955":
  friendly_name: living_room_bulb_1
  homeassistant: null
"0x000d6ffffe529ec7":
  friendly_name: living_room_bulb_2
  homeassistant: null
"0x000d6ffffe62f264":
  friendly_name: living_room_bulb_3
  homeassistant: null
"0x000d6ffffe4b01bb":
  friendly_name: living_room_bulb_4
  homeassistant: null
"0x000d6ffffe52a044":
  friendly_name: living_room_bulb_5
  homeassistant: null

# Occupancy Sensors
"0x00158d0006a0cd1e":
  friendly_name: living_room_occupancy_sensor
  occupancy_timeout: 600
  homeassistant:
    device:
      name: Living Room Occupancy Sensor
    illuminance_lux:
      name: Living Room Illuminance Lux
    occupancy:
      name: Living Room Occupancy
    battery:
      name: Living Room Occupancy Sensor Battery

"0x00158d0006a155e9":
  friendly_name: dining_room_occupancy_sensor
  occupancy_timeout: 600
  homeassistant:
    device:
      name: Dining Room Occupancy Sensor
    illuminance_lux:
      name: Dining Room Illuminance Lux
    occupancy:
      name: Dining Room Occupancy
    battery:
      name: Dining Room Occupancy Sensor Battery

"0x00158d0006a1590f":
  friendly_name: bedroom_occupancy_sensor
  occupancy_timeout: 600
  homeassistant:
    device:
      name: Bedroom Occupancy Sensor
    illuminance_lux:
      name: Bedroom Illuminance Lux
    occupancy:
      name: Bedroom Occupancy
    battery:
      name: Bedroom Occupancy Sensor Battery

"0x00158d00068a31f7":
  friendly_name: kids_room_occupancy_sensor
  occupancy_timeout: 600
  homeassistant:
    device:
      name: Kids Room Occupancy Sensor
    illuminance_lux:
      name: Kids Room Illuminance Lux
    occupancy:
      name: Kids Room Occupancy
    battery:
      name: Kids Room Occupancy Sensor Battery

# Repeater
"0xbc33acfffe2b49c5":
  friendly_name: kitchen_repeater
  homeassistant:
    device:
      name: Kitchen Repeater
    update_available:
      name: Kitchen Repeater Update Available

# Philips Hue Dimmer and LED strips
"0x00178801103985a9":
  friendly_name: hue_dimmer_switch
  homeassistant:
    device:
      name: Hue Dimmer Switch
    battery:
      name: Hue Dimmer Switch Battery
    update_available:
      name: Hue Dimmer Switch Update Available

"0x00178801011bfef8":
  friendly_name: kitchen_led_strip_ceiling
  homeassistant:
    device:
      name: Kitchen LED Strip Ceiling
    light:
      name: Kitchen LED Strip Ceiling
      icon: mdi:led-strip-variant
    update_available:
      name: Kitchen LED Strip Ceiling Update Available
"0x0017880100cb1a50":
  friendly_name: kitchen_led_strip_floor_wall
  homeassistant:
    device:
      name: Kitchen LED Strip Floor Wall
    light:
      name: Kitchen LED Strip Floor Wall
      icon: mdi:led-strip-variant
    update_available:
      name: Kitchen LED Strip Floor Wall Update Available

"0x0017880100cb1a57":
  friendly_name: kitchen_led_strip_floor_island
  homeassistant:
    device:
      name: Kitchen LED Strip Floor Island
    light:
      name: Kitchen LED Strip Floor Island
      icon: mdi:led-strip-variant
    update_available:
      name: Kitchen LED Strip Floor Island Update Available

# Ikea Tradfri Control Outlet
"0xcc86ecfffe98e1f2":
  friendly_name: dna_lamp
  homeassistant:
    device:
      name: DNA Lamp
    switch:
      name: DNA Lamp
    power_on_behavior:
      name: DNA Lamp Power on Behavior

"0xcc86ecfffe951e11":
  friendly_name: plug_switch_1_unused
  homeassistant:
    device:
      name: Plug Switch 1
    switch:
      name: Plug Switch 1
    power_on_behavior:
      name: Plug Switch 1 Power on Behavior

"0xcc86ecfffe9fc60b":
  friendly_name: plug_switch_2
  homeassistant:
    device:
      name: Plug Switch 2
    switch:
      name: Plug Switch 2
    power_on_behavior:
      name: Plug Switch 2 Power on Behavior
